# -*- coding: utf-8 -*-
"""pg_1st_phase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lIqWvKNLhELbL2pf9ruazifaWhvEkmOL
"""

!pip -q install gurobipy==11.0.3

import gurobipy as gp
from gurobipy import GRB, GurobiError

WLS_ACCESS_ID = "WLS_ACCESS_ID"
WLS_SECRET = "WLS_SECRET"
LICENSE_ID = LICENSE_ID

GLOBAL_ENV = gp.Env(empty=True)
GLOBAL_ENV.setParam("WLSAccessID", WLS_ACCESS_ID)
GLOBAL_ENV.setParam("WLSSecret", WLS_SECRET)
GLOBAL_ENV.setParam("LICENSEID", LICENSE_ID)
GLOBAL_ENV.start()

import math, random, csv, os, statistics, numpy as np
from dataclasses import dataclass
from typing import List, Tuple, Dict
from pathlib import Path
import matplotlib.pyplot as plt
import torch, torch.nn as nn
import torch.nn.functional as F
import torch.distributions as D
import gurobipy as gp
from gurobipy import GRB


# Randomness
SEED = 42

# RL basics
GAMMA = 0.95
ENT0, ENT_DECAY = 0.2, 1.0
LR = 0.01
GRAD_CLIP = 10.0

# Modifier output ranges
W_MIN, W_MAX = 0.0, 5.0
CLIP_MAX_B = 1.5
CLIP_MAX_DQ = 1.0

# Initial exploration std
STD_B0, STD_W0, STD_DQ0 = 1.0, 1.0, 1.0
STD_DECAY = 1.0
# Important! STD_DECAY < 1.0 leads to coeficients converging to a constant value
# This means that after some epochs there is no difference between policy mod
# and the un-modified MILP

# Curriculum phases
CURR_W_ONLY_EP  = 1000
CURR_WB_ONLY_EP = 2000
ENABLE_DQ_PHASE = False

# Slack gating
SLACK_GATE = 0.20
B_PENALTY  = 0.10
DQ_PENALTY = 0.05

# Environment / geometry
DT = 20.0
SERVICE_TIME = 1.0
AREA = 50.0

REQUESTS_PER_EPOCH = 20
N_VEH = 6
VEH_CAP = 4
GRID_SIDE = 20
EP_STEPS = 60

# MILP solver
TIME_LIMIT_MIP = 5.0

# Training
TRAIN_EPISODES = 2000 # I had not thought of this, but a lot of epochs are needed
                      # (Ideally even more than 20k). The problem is very high-dim,
                      # so a lot of epochs are needed to explore meaningfully
                      # the state and action spaces
EVAL_EPISODES = 50
EVAL_EVERY = 100
SNAP_EVAL_EPISODES = 50

# Output
OUTDIR = "report_runs_pg"

# Types
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)

NodeId = int
Action = Dict[int, List[Tuple[int, int]]]

@dataclass
class Vehicle:
    id:int; capacity:int; time:float; node:NodeId; load:int=0

@dataclass
class State:
    T:float; t:float; tt:np.ndarray; coords:List[Tuple[float,float]]; vehicles:List[Vehicle]

@dataclass
class Request:
    pickup: int
    drop: int
    pax: int
    deadline: float
    base_value: float = 1.0

# === GEOMETRY / DEMAND ===
def make_grid(n_side:int, area:float):
    coords=[]; step=area/(n_side-1) if n_side>1 else 0.0
    for r in range(n_side):
        for c in range(n_side):
            coords.append((r*step, c*step))
    N=n_side*n_side
    tt=np.zeros((N,N),dtype=float)
    for i,(xi,yi) in enumerate(coords):
        for j,(xj,yj) in enumerate(coords):
            tt[i,j]=0.0 if i==j else math.hypot(xi-xj, yi-yj)
    return coords, tt

def generate_request(state: State, pax_min=1, pax_max=2, slack_low=0.5, slack_high=2.0):
    N = len(state.coords)
    p = random.randrange(N)
    d = random.randrange(N)
    while d == p:
        d = random.randrange(N)

    pax = random.randint(pax_min, pax_max)
    travel = state.tt[p, d]
    deadline = state.t + travel + 2*SERVICE_TIME + random.uniform(slack_low, slack_high)
    base_value = 1.0  # Default base value

    # Here are some alternative strategies that give more value to certain trips
    # with respect to others. We can use these as an extra check, to see if the policy
    # modification learns to prioritize higher-value trips

    # Alternative Strategy 2: High-occupancy trips are more valuable
    # base_value = float(pax)  # 1-passenger = 1.0, 2-passenger = 2.0

    # Alternative Strategy 3: Random heterogeneity (10% premium requests)
    # base_value = 3.0 if random.random() < 0.1 else 1.0

    # Alternative Strategy 4: Location-based (downtown more valuable)
    # downtown_nodes = set(range(N//4, 3*N//4))  # Central area
    # base_value = 2.0 if (p in downtown_nodes or d in downtown_nodes) else 1.0

    return Request(pickup=p, drop=d, pax=pax, deadline=deadline, base_value=base_value)

# ========= MILP ==========
def solve_epoch_milp_modified(state:State, pending:List[Request],
                              weights:List[float], cap_tighten:List[float], deadline_tighten:List[float],
                              timelimit=TIME_LIMIT_MIP):
    """
    Solve a *single-assignment* epoch MILP on the MODIFIED instance:
      - Per-request reward (weight) can vary (prioritization)
      - Per-vehicle capacity is only decreased (cap - ΔQ >= 0).
      - Per-request deadline can only be tightened (deadline - b, with b ≥ 0 and ≤ slack).
    Feasibility domain is a subset of the original (Ω(mod) ⊆ Ω(orig)).
    Returns: (action, served_idx, milp_diag)
    """
    V=list(range(len(state.vehicles))); K=list(range(len(pending)))
    v_node=[state.vehicles[v].node for v in V]; v_time=[state.vehicles[v].time for v in V]
    base_cap=[state.vehicles[v].capacity for v in V]
    eff_cap=[max(0.0, base_cap[v]-float(cap_tighten[v])) for v in V]

    eff_dead=[]
    for k in K:
        r=pending[k]
        min_time=state.tt[r.pickup,r.drop]+2*SERVICE_TIME
        slack=max(0.0,(r.deadline-state.t)-min_time)
        b=min(max(0.0,float(deadline_tighten[k])), slack)
        eff_dead.append(max(state.t, r.deadline-b))

    feas={(v,k):1 for v in V for k in K}
    for v in V:
      for k in K:
          r=pending[k]

          # Check if vehicle is available at current time
          if v_time[v] > state.t:
              feas[(v,k)] = 0
              continue

          if r.pax>eff_cap[v]: feas[(v,k)]=0; continue
          arr_p=v_time[v]+state.tt[v_node[v],r.pickup]+SERVICE_TIME
          arr_d=arr_p+state.tt[r.pickup,r.drop]+SERVICE_TIME
          if arr_d>eff_dead[k]: feas[(v,k)]=0; continue

    m = gp.Model("epoch_mod", env=GLOBAL_ENV)
    m.Params.OutputFlag = 0
    m.Params.TimeLimit = timelimit
    x = m.addVars(V, K, vtype=GRB.BINARY, name="x")

    for k in K: m.addConstr(gp.quicksum(x[v,k] for v in V) <= 1)
    for v in V:
        m.addConstr(gp.quicksum(x[v,k] for k in K) <= 1)
        m.addConstr(gp.quicksum(pending[k].pax*x[v,k] for k in K if feas[(v,k)]==1) <= eff_cap[v])
    for v in V:
        for k in K:
            if feas[(v,k)]==0: m.addConstr(x[v,k]==0)

    m.setObjective(gp.quicksum(float(weights[k])*x[v,k] for v in V for k in K if feas[(v,k)]==1), GRB.MAXIMIZE)
    m.optimize()

    # collect solver diagnostics
    status  = int(m.Status)
    runtime = float(getattr(m, "Runtime", float("nan")))
    mipgap  = float(getattr(m, "MIPGap", float("nan")))
    milp_diag = dict(status=status, runtime=runtime, mipgap=mipgap)

    # Extract ALL assignments (all vehicles)
    action:Action={}
    served_idx=[]

    for v in V:
        for k in K:
            if feas[(v,k)]==1 and x[v,k].X > 0.5:
                req=pending[k]
                action[v]=[(state.vehicles[v].node, req.pickup),(req.pickup, req.drop)]
                served_idx.append(k)
                # NO BREAK - keep checking (though MILP ensures at most 1 per vehicle)
                # There was a problem here: the MILP was assigning always a single
                # vehicle, even if multiple were available.

    return action, served_idx, milp_diag

# ====== STATE UPDATE =====
# This was embedded in step_sim, to handle multiple vehicles and not just one

# ========= FEATURES ======
def req_features(state:State, pending:List[Request]):
    feats=[]
    for r in pending:
        trip=state.tt[r.pickup,r.drop]
        slack=(r.deadline-state.t)-(trip+2*SERVICE_TIME)
        feats.append([trip, r.pax, max(0.0,slack), float(r.pickup), float(r.drop)])
    if not feats: feats=[[0,0,0,0,0]]
    M=max(1,len(state.coords)-1)
    f=np.array(feats,dtype=np.float32)
    f[:,0]=f[:,0]/(AREA*2+1e-6)
    f[:,1]=f[:,1]/max(1,VEH_CAP)
    f[:,2]=f[:,2]/5.0
    f[:,3]=f[:,3]/M; f[:,4]=f[:,4]/M
    return f

def veh_features(state:State):
    feats=[]; N=len(state.coords); M=max(1,N-1)
    for v in state.vehicles:
        feats.append([float(v.node)/M, max(0.0, v.time-state.t)])
    f=np.array(feats,dtype=np.float32)
    if f.size==0: f=np.zeros((1,2),dtype=np.float32)
    f[:,1]=np.clip(f[:,1],0.0,5.0)/5.0
    return f

def global_features(state:State, pending:List[Request]):
    rfe=req_features(state,pending)
    slack_stats=[rfe[:,2].min(),rfe[:,2].max(),rfe[:,2].mean()] if len(rfe)>0 else [0,0,0]
    t_phase=(state.t%max(1e-6,state.T))/max(1e-6,state.T)
    feas_count = 0
    for v in state.vehicles:
        for r in pending:
            arrp = v.time + state.tt[v.node, r.pickup] + SERVICE_TIME
            arrd = arrp + state.tt[r.pickup, r.drop] + SERVICE_TIME
            feas_count += int(arrd <= r.deadline and r.pax <= v.capacity)
    denom = max(1, len(state.vehicles) * len(pending))
    feas_density = feas_count / denom
    return np.array([t_phase, len(pending)/8.0, slack_stats[0], slack_stats[1], slack_stats[2], feas_density], dtype=np.float32)

# ===== POLICY & CRITIC ===

"""
=== KEY CHANGES FROM PREVIOUS VERSION ===
(IMPORTANT! @Mansi, this is partially AI generated. I have read it and modified some parts,
and to me it seems clear enough,
but let me know if there are things you don't understand!)

1. ARCHITECTURE FIX (ModifierNet):
   Problem: The old architecture had a "shared bottleneck" where global features were
            compressed to h dimensions BEFORE being combined with request features.
            This caused all requests to get similar weights (uniform outputs).
            Intuitively, this is because the global features were mapped to a vector
            whose dimensions (64) was much larger than the request features (5).

   Solution: Now we concatenate [global_features, request_features] FIRST, then process
             them together. Each request gets its own information pathway through the network.

   Old flow: global → compress(h dims) → [h_global + request_features] → output
   New flow: [global + request_features] → process together → output

   Result: The network can now learn different weights for different requests!

2. MULTI-VEHICLE BUG FIX (step_sim):
   Problem: The old apply_action() function only updated ONE vehicle per epoch:
            (v_id, route) = next(iter(action.items()))  # Only first vehicle!

   Solution: Removed apply_action() and inlined the logic in step_sim() to loop over
             ALL vehicles:
            for v_id, route in action.items():  # All vehicles now!

   Result: Multiple vehicles can be assigned simultaneously (as intended by MILP).

3. CREDIT ASSIGNMENT CHANGE (Training loop):
   Problem: Old approach updated gradients for ALL requests (served + rejected).
            This is noisy because rejected requests might be infeasible anyway.
            In other words you don't want to modify the policy looking at policies that
            were infeasible anyway.

   Solution: Now we only update gradients for requests that were ACTUALLY SERVED.
             We store per-request log-probs (logp_w_vec) and only backprop through
             the served ones:

            for t in range(len(logp_w_steps)):
                served = served_steps[t]  # Which requests were served?
                if len(served) > 0:
                    lp_served = logp_w_vec.index_select(0, served).sum()
                    pg_terms.append(-advantage[t] * lp_served)  # Only these!

   Why? Only served requests directly contributed to the reward. Rejected requests
        might have been correctly rejected (infeasible deadline, wrong location, etc).
        This gives cleaner learning signal: "these weights led to good assignments.

4. BETTER INITIALIZATION:
   Changed from zero-init to orthogonal initialization (gain=0.5) for more stable
   early training and better gradient flow. (Honestly, I don't think this changes much,
   it was suggested by the AI)

5. REWARD BASED ON BASE_VALUE:
   Training reward now uses request.base_value instead of just counting served requests.
   This allows testing whether the policy learns to prioritize high-value trips.
   (Currently base_value=1.0 for all, but you can change generate_request() to test)
"""

class ModifierNet(nn.Module):
    """
    π_MOD: outputs per-request (b_k deadline tighten, w_k reward weight) and per-vehicle (ΔQ_v capacity tighten).
    Range constraints enforce “only tighten / decrease” and permit negative rewards (W_MIN < 0).
    """
    def __init__(self,d_global=6,d_req=5,d_veh=2,h=64):
        super().__init__()
        print("Loading policy...")
        # Per-request processing (NO shared global bottleneck)
        self.req_encoder = nn.Sequential(
            nn.Linear(d_req + d_global, h),
            nn.ReLU(),
            nn.Linear(h, h),
            nn.ReLU()
        )
        self.req_head = nn.Sequential(
            nn.Linear(h, h),
            nn.ReLU(),
            nn.Linear(h, 2)  # [b_raw, w_raw]
        )

        # Per-vehicle processing
        self.veh_encoder = nn.Sequential(
            nn.Linear(d_veh + d_global, h),
            nn.ReLU(),
            nn.Linear(h, h),
            nn.ReLU()
        )
        self.veh_head = nn.Sequential(
            nn.Linear(h, h),
            nn.ReLU(),
            nn.Linear(h, 1)  # [dq_raw]
        )

        self.logstd_b=nn.Parameter(torch.tensor(math.log(STD_B0)))
        self.logstd_w=nn.Parameter(torch.tensor(math.log(STD_W0)))
        self.logstd_dq=nn.Parameter(torch.tensor(math.log(STD_DQ0)))

        # Better initialization
        with torch.no_grad():
            for m in self.modules():
                if isinstance(m, nn.Linear):
                    nn.init.orthogonal_(m.weight, gain=0.5)
                    if m.bias is not None:
                        nn.init.zeros_(m.bias)

    @staticmethod
    def _sq_b(y):  return CLIP_MAX_B*torch.sigmoid(y)
    @staticmethod
    def _sq_w(y):  return W_MIN+(W_MAX-W_MIN)*torch.sigmoid(y)
    @staticmethod
    def _sq_dq(y): return CLIP_MAX_DQ*torch.sigmoid(y)

    def forward_means(self,gvec,rmat,vmat):
        # Expand global to match batch
        g_expanded_req = gvec.unsqueeze(0).expand(rmat.shape[0], -1) if rmat.shape[0] > 0 else gvec.unsqueeze(0)
        g_expanded_veh = gvec.unsqueeze(0).expand(vmat.shape[0], -1) if vmat.shape[0] > 0 else gvec.unsqueeze(0)

        # Process each request independently
        if rmat.shape[0] > 0:
            req_input = torch.cat([rmat, g_expanded_req], dim=1)
            req_encoded = self.req_encoder(req_input)
            mu_req = self.req_head(req_encoded)
        else:
            mu_req = torch.zeros(1, 2, device=gvec.device)

        # Process each vehicle independently
        if vmat.shape[0] > 0:
            veh_input = torch.cat([vmat, g_expanded_veh], dim=1)
            veh_encoded = self.veh_encoder(veh_input)
            mu_veh = self.veh_head(veh_encoded).squeeze(-1)
        else:
            mu_veh = torch.zeros(1, device=gvec.device)

        return mu_req, mu_veh

    def sample(self, gvec, rmat, vmat, allow_b=True, allow_dq=False, slack_gate=SLACK_GATE):
      mu_req, mu_veh = self.forward_means(gvec, rmat, vmat)
      dist_b  = D.Normal(mu_req[:,0], self.logstd_b.exp())
      dist_w  = D.Normal(mu_req[:,1], self.logstd_w.exp())
      dist_dq = D.Normal(mu_veh,     self.logstd_dq.exp())

      b_raw  = dist_b.rsample()
      w_raw  = dist_w.rsample()
      dq_raw = dist_dq.rsample()

      b_k  = self._sq_b(b_raw)
      w_k  = self._sq_w(w_raw)
      dq_v = self._sq_dq(dq_raw)

      # slack gating for b
      if rmat.numel() > 0:
          mask = (rmat[:,2] > slack_gate).float()
      else:
          mask = torch.zeros_like(b_k)

      if allow_b:  b_k = b_k * mask
      else:        b_k = torch.zeros_like(b_k)
      if not allow_dq: dq_v = torch.zeros_like(dq_v)

      # === build loss pieces only for enabled heads ===
      # Why separate losses? During curriculum learning, we enable heads gradually:
      #   Phase 1 (eps 1-1000):    only w (weights) - learn basic prioritization
      #   Phase 2 (eps 1001-2000): w + b (deadlines) - learn to tighten time windows
      #   Phase 3 (eps 2001+):     w + b + ΔQ (capacity) - learn capacity management
      #
      # We ONLY compute gradients for active heads. Otherwise:
      #   - Inactive heads get random gradients (they're not used by MILP)
      #   - This adds noise and slows learning
      #   - Wastes compute on unused parameters
      #
      # So we build logp and entropy terms conditionally:
      logp_terms = [dist_w.log_prob(w_raw).sum()]  # w always active
      ent_terms  = [dist_w.entropy().sum()]

      if allow_b:  # Add b terms only if deadline tightening is enabled
          logp_terms.append(dist_b.log_prob(b_raw).sum())
          ent_terms.append(dist_b.entropy().sum())

      if allow_dq:  # Add ΔQ terms only if capacity modification is enabled
          logp_terms.append(dist_dq.log_prob(dq_raw).sum())
          ent_terms.append(dist_dq.entropy().sum())

      logp = torch.stack(logp_terms).sum()
      ent  = torch.stack(ent_terms).sum()

      # Result: Gradients only flow through heads that are actually being used!

      # return also per-request log-prob for w to enable per-served credit
      logp_w_vec = dist_w.log_prob(w_raw)    # shape [K], keep grads
      ent_w_vec  = dist_w.entropy()          # shape [K]

      return (
          b_k.detach().numpy().tolist(),
          dq_v.detach().numpy().tolist(),
          w_k.detach().numpy().tolist(),
          logp, ent, float(mask.mean()),
          logp_w_vec, ent_w_vec
      )

    def deterministic(self,gvec,rmat,vmat, allow_b=True, allow_dq=False, slack_gate=SLACK_GATE):
        mu_req,mu_veh=self.forward_means(gvec,rmat,vmat)
        b=self._sq_b(mu_req[:,0]); dq=self._sq_dq(mu_veh); w=self._sq_w(mu_req[:,1])

        if rmat.numel() > 0:
            slack=rmat[:,2]; mask=(slack > slack_gate).float()
        else:
            mask = torch.zeros_like(b)

        if allow_b:  b = b * mask
        else:        b = torch.zeros_like(b)
        if not allow_dq: dq = torch.zeros_like(dq)

        return b.detach().numpy().tolist(), dq.detach().numpy().tolist(), w.detach().numpy().tolist()

class Critic(nn.Module):
    def __init__(self,d_global=6,h=64):
        super().__init__()
        print("Loading critic...")
        self.net=nn.Sequential(nn.Linear(d_global,h),nn.ReLU(),nn.Linear(h,1))
    def forward(self,g): return self.net(g).squeeze(-1)

# ===== PHASE / GATING ====
def phase_for_ep(ep:int):
    if ep <= CURR_W_ONLY_EP:  return "w"
    if ep <= CURR_WB_ONLY_EP: return "wb"
    return "full"

def phase_to_gates(phase:str):
    if phase=="w":    return dict(allow_b=False, allow_dq=False)
    if phase=="wb":   return dict(allow_b=True,  allow_dq=False)
    return dict(allow_b=True, allow_dq=ENABLE_DQ_PHASE)

# ===== ENV HELPERS =======
def make_initial_state(coords, tt, n_vehicles=N_VEH):
    """Create initial state with specified number of vehicles"""
    vehicles = []
    N = len(coords)

    # Distribute vehicles across the grid
    for i in range(n_vehicles):
        if i == 0:
            node = 0  # First corner
        elif i == 1:
            node = N - 1  # Opposite corner
        else:
            # Spread remaining vehicles
            node = int((i / n_vehicles) * N)

        vehicles.append(Vehicle(id=i, capacity=VEH_CAP, time=0.0, node=node))

    return State(T=10.0, t=0.0, tt=tt, coords=coords, vehicles=vehicles)

def plan_epoch_with_pg_modifiers(state, pending, policy, allow_b, allow_dq):
    g = torch.tensor(global_features(state, pending), dtype=torch.float32)
    r = torch.tensor(req_features(state, pending), dtype=torch.float32)
    v = torch.tensor(veh_features(state), dtype=torch.float32)
    return policy.sample(g, r, v, allow_b=allow_b, allow_dq=allow_dq, slack_gate=SLACK_GATE), g


def step_sim(state: State, pending: List[Request], weights, dq_v, b_k, debug=False):
    """
    Execute one epoch: solve MILP with modified parameters and update state.

    Debug mode (debug=True):
    When debugging is enabled, prints detailed information about the decision process:
      - Current time and pending request queue
      - For each request: pickup→drop, passengers, trip length, slack time, weight, base_value
      - Vehicle availability (location and time)
      - MILP assignment decisions (which vehicle serves which request)
      - Final reward calculation (base_value × weight for served requests)

    Use this to understand:
      1. Why certain requests are/aren't served (feasibility, weights, vehicle availability)
      2. Whether the policy is learning to assign high weights to valuable requests
      3. How the MILP solver is making assignment decisions

    Typical usage in run_episode_pg():
      debug_epochs=[0, 10, 20] if ep in [1, 5, 30] else None
      # This debugs epochs 0,10,20 of episodes 1,5,30 to see learning progress
    """
    action, served, milp_diag = solve_epoch_milp_modified(state, pending, weights, dq_v, b_k, TIME_LIMIT_MIP)

    # Debug output
    if debug:
        print(f"\n  Time t={state.t:.1f}")
        print(f"  Pending requests: {len(pending)}")
        for i, req in enumerate(pending):
            trip_len = state.tt[req.pickup, req.drop]
            slack = req.deadline - state.t - trip_len - 2*SERVICE_TIME
            print(f"    Req {i}: ({req.pickup}→{req.drop}) pax={req.pax} trip={trip_len:.2f} slack={slack:.2f} w={weights[i]:.3f} BASE_VALUE={req.base_value:.1f}")  # NEW: Show base value

        print(f"  Vehicle states:")
        for v in state.vehicles:
            print(f"    Veh {v.id}: at node {v.node}, available at t={v.time:.1f}")

        if action:
            print(f"  → Assigned {len(action)} vehicles:")
            for v_id, route in action.items():
                req_idx = served[list(action.keys()).index(v_id)]
                req = pending[req_idx]
                print(f"     Veh {v_id} serves Req {req_idx} (w={weights[req_idx]:.3f}, base_value={req.base_value:.1f}, reward={req.base_value * weights[req_idx]:.3f})")
        else:
            print(f"  → No assignment (all infeasible)")

    # Reward = sum of BASE VALUES of served requests (If base_value==1.0 the it's the normal MILP)
    r_train = sum(pending[k].base_value for k in served) if served else 0.0
    count_served = len(served)

    # Penalties (unchanged)
    if B_PENALTY > 0 and len(b_k) > 0:
        r_train -= B_PENALTY * float(np.mean(b_k))
    if DQ_PENALTY > 0 and len(dq_v) > 0:
        r_train -= DQ_PENALTY * float(np.mean(dq_v))

    # Apply ALL vehicle actions
    if action:
        for v_id, route in action.items():
            v = state.vehicles[v_id]
            t = v.time
            node = v.node
            for (i, j) in route:
                t += state.tt[i, j] + SERVICE_TIME
                node = j
            v.time = t
            v.node = node

    # Remove served requests from pending queue (unchanged)
    for idx in sorted(served, reverse=True):
        pending.pop(idx)

    state.t += DT
    return r_train, count_served, served, pending, milp_diag

# ===== EPISODE ROLLOUT ===
def run_episode_pg(coords,tt,policy:ModifierNet,critic:Critic=None,ent_coef=0.0, phase="w", debug_epochs=None):
    """
    debug_epochs: list of epoch indices to print detailed debug info (e.g., [0, 10, 20])
    """
    gates = phase_to_gates(phase)
    st=make_initial_state(coords,tt); pending=[]; logps=[]; ents=[]; train_rewards=[]; true_counts=[]; gbuf=[]
    diag_avg_b=[]; diag_gate_frac=[]; diag_avg_dq=[]
    diag_neg_w=[]; diag_feas=[]; diag_ent=[]
    diag_mip_status=[]; diag_mip_runtime=[]; diag_mip_gap=[]
    diag_queue_size=[]; diag_avg_w=[]; diag_std_w=[]; diag_min_w=[]; diag_max_w=[]

    # buffers before the loop
    logp_w_steps = []
    ent_w_steps  = []
    served_steps = []

    for epoch_idx in range(EP_STEPS):
        debug_this_epoch = debug_epochs is not None and epoch_idx in debug_epochs

        if debug_this_epoch:
            print(f"\n{'='*60}")
            print(f"EPOCH {epoch_idx}/{EP_STEPS}")
            print(f"{'='*60}")

        for _ in range(REQUESTS_PER_EPOCH):
            req=generate_request(st, slack_low=0.0, slack_high=0.1) # Increased slack
            pending.append(req)

        pending=[r for r in pending if r.deadline>=st.t]
        diag_queue_size.append(len(pending))
        (out, g) = plan_epoch_with_pg_modifiers(st, pending, policy, **gates)
        (b, dq, w, logp_scalar, ent_scalar, gate_frac, logp_w_vec, ent_w_vec) = out

        # keep scalar diagnostics if you still want them:
        logps.append(logp_scalar)
        ents.append(ent_scalar)
        diag_ent.append(float(ent_scalar))   # <-- add this line

        r_train, count, served, pending, milp_d = step_sim(st, pending, w, dq, b, debug=debug_this_epoch)

        # store the per-request vectors & served indices for this step
        logp_w_steps.append(logp_w_vec)   # tensor length K_t
        ent_w_steps.append(ent_w_vec)     # tensor length K_t
        served_steps.append(served)       # python list of ints

        if debug_this_epoch:
            print(f"\nModifier outputs:")
            print(f"  Weight stats: min={min(w) if w else 0:.3f} max={max(w) if w else 0:.3f} mean={np.mean(w) if w else 0:.3f} std={np.std(w) if w else 0:.3f}")


        train_rewards.append(r_train)
        true_counts.append(count)
        gbuf.append(g)

        diag_avg_b.append(float(np.mean(b)) if len(b)>0 else 0.0)
        diag_gate_frac.append(gate_frac)
        diag_avg_dq.append(float(np.mean(dq)) if len(dq)>0 else 0.0)
        diag_avg_w.append(float(np.mean(w)) if len(w)>0 else 1.0)
        diag_std_w.append(float(np.std(w)) if len(w)>1 else 0.0)
        diag_min_w.append(float(np.min(w)) if len(w)>0 else 1.0)
        diag_max_w.append(float(np.max(w)) if len(w)>0 else 1.0)

        neg_w_frac = float(np.mean(np.array(w) < 1.0)) if len(w)>0 else 0.0
        diag_neg_w.append(neg_w_frac)
        diag_feas.append(float(g[5].item()))
        diag_mip_status.append(milp_d["status"])
        diag_mip_runtime.append(milp_d["runtime"])
        diag_mip_gap.append(milp_d["mipgap"])

    # Returns from training rewards
    G=[]; acc=0.0
    for r in reversed(train_rewards):
        acc=r+GAMMA*acc; G.append(acc)
    G=list(reversed(G))
    G_t=torch.tensor(G,dtype=torch.float32)
    gstack=torch.stack(gbuf)

    if critic is None:
        adv=G_t
        v_for_loss = G_t.detach()
    else:
        with torch.no_grad():
            bval=critic(gstack)
        adv = G_t - bval
        v_for_loss = G_t.detach()
        adv = (adv - adv.mean())/(adv.std()+1e-6)

    diag = dict(
        avg_b=float(np.mean(diag_avg_b)),
        gate_frac=float(np.mean(diag_gate_frac)),
        avg_dq=float(np.mean(diag_avg_dq)),
        neg_w_frac=float(np.mean(diag_neg_w)),
        feas_density=float(np.mean(diag_feas)),
        ent=float(np.mean(diag_ent)),
        mip_status=int(round(statistics.mean(diag_mip_status))) if len(diag_mip_status)>0 else -1,
        mip_runtime=float(np.mean(diag_mip_runtime)),
        mip_gap=float(np.nanmean(diag_mip_gap)) if np.any(~np.isnan(diag_mip_gap)) else float("nan"),
        avg_queue_size=float(np.mean(diag_queue_size)),
        max_queue_size=float(np.max(diag_queue_size)),
        avg_w=float(np.mean(diag_avg_w)),
        std_w=float(np.mean(diag_std_w)),
        min_w=float(np.mean(diag_min_w)),
        max_w=float(np.mean(diag_max_w)),
    )

    total_served = sum(true_counts)
  # Return ONLY what we need; drop old logps/ents
    return v_for_loss, G_t, adv, gstack, total_served, diag, logp_w_steps, ent_w_steps, served_steps


def run_episode_pg_eval(coords,tt,policy:ModifierNet, phase="w"):
    gates = phase_to_gates(phase)
    st=make_initial_state(coords,tt); pending=[]; tot=0
    for _ in range(EP_STEPS):
        for _ in range(REQUESTS_PER_EPOCH):
            req=generate_request(st)
            pending.append(req)

        pending=[r for r in pending if r.deadline>=st.t]
        g=torch.tensor(global_features(st,pending),dtype=torch.float32)
        rfe=torch.tensor(req_features(st,pending),dtype=torch.float32)
        vfe=torch.tensor(veh_features(st),dtype=torch.float32)
        b,dq,w = policy.deterministic(g,rfe,vfe, **gates)

        action,served,_ = solve_epoch_milp_modified(st,pending,w,dq,b,TIME_LIMIT_MIP)
        tot+=len(served)

        # Apply ALL vehicle actions
        if action:
            for v_id, route in action.items():
                v = st.vehicles[v_id]
                t = v.time
                node = v.node
                for (i, j) in route:
                    t += st.tt[i, j] + SERVICE_TIME
                    node = j
                v.time = t
                v.node = node

        for idx in sorted(served,reverse=True): pending.pop(idx)
        st.t+=DT
    return tot

# ======== TRAINING =======
def train_single_seed(seed, outdir=OUTDIR, log_curve=True):
    print(f"Beginning training for seed {seed}...")
    random.seed(seed); np.random.seed(seed); torch.manual_seed(seed)
    print("Loading coords and tt...")
    coords,tt=make_grid(GRID_SIDE,AREA)
    policy=ModifierNet()
    critic=Critic()
    ent_coef = ENT0
    opt_p=torch.optim.Adam(policy.parameters(), lr=LR)
    opt_c=torch.optim.Adam(critic.parameters(), lr=LR)

    ep_returns=[]; std_scale=1.0
    snap_evals = []  # NEW: Track snap eval performance
    best_eval=-1e-9; best_state=None
    diag_rows=[]

    for ep in range(1, TRAIN_EPISODES+1):
        phase = phase_for_ep(ep)

        with torch.no_grad():
            policy.logstd_b.data  = torch.log(torch.clamp(torch.exp(policy.logstd_b)*std_scale, 1e-3, 1.0))
            policy.logstd_w.data  = torch.log(torch.clamp(torch.exp(policy.logstd_w)*std_scale, 1e-3, 1.0))
            policy.logstd_dq.data = torch.log(torch.clamp(torch.exp(policy.logstd_dq)*std_scale, 1e-3, 1.0))

        v_target, G_t, adv, gstack, total_served, diag, logp_w_steps, ent_w_steps, served_steps = run_episode_pg(
            coords, tt, policy, critic, ent_coef, phase=phase,
            debug_epochs=None
            #debug_epochs=[0, 10, 20] if ep in [1, 5, 30] else None  # Debug first 3 epochs of episodes 1, 5, 30
        )
        ep_returns.append(total_served)

        diag_rows.append({
            "episode": ep,
            "phase": phase,
            "avg_b": diag["avg_b"],
            "gate_frac": diag["gate_frac"],
            "avg_dq": diag["avg_dq"],
            "neg_w_frac": diag["neg_w_frac"],
            "feas_density": diag["feas_density"],
            "ent": diag["ent"],
            "mip_status": diag["mip_status"],
            "mip_runtime": diag["mip_runtime"],
            "mip_gap": diag["mip_gap"],
            "served": total_served,
            "avg_queue_size": diag["avg_queue_size"],
            "max_queue_size": diag["max_queue_size"],
            "avg_w": diag["avg_w"],
            "std_w": diag["std_w"],
            "min_w": diag["min_w"],
            "max_w": diag["max_w"],
        })

        # Critic update
        pred=critic(gstack)
        v_loss=F.mse_loss(pred, v_target)
        opt_c.zero_grad(); v_loss.backward(); nn.utils.clip_grad_norm_(critic.parameters(), GRAD_CLIP); opt_c.step()

        # === Policy update: served-only credit assignment ===
        at = adv.detach()  # REINFORCE: treat advantage as constant
        pg_terms  = []
        ent_terms = []
        for t in range(len(logp_w_steps)):
            lp_vec  = logp_w_steps[t]    # tensor [K_t]
            ent_vec = ent_w_steps[t]     # tensor [K_t]
            served  = served_steps[t]    # list[int]

            if len(served) > 0:
                idx = torch.tensor(served, dtype=torch.long, device=lp_vec.device)
                lp_served  = lp_vec.index_select(0, idx).sum()
                ent_served = ent_vec.index_select(0, idx).sum()
            else:
                zero = lp_vec.sum() * 0.0
                lp_served  = zero
                ent_served = zero

            pg_terms.append(- at[t] * lp_served)
            ent_terms.append(- ent_coef * ent_served)

        pg_loss = torch.stack(pg_terms).sum() + torch.stack(ent_terms).sum()

        opt_p.zero_grad()
        pg_loss.backward()
        nn.utils.clip_grad_norm_(policy.parameters(), GRAD_CLIP)
        opt_p.step()

        ent_coef *= ENT_DECAY

        if (ep % 100) == 0 and log_curve:
            print(f"[train s{seed}] ep={ep:04d} served={total_served:.1f} queue={diag['avg_queue_size']:.1f} w={diag['min_w']:.2f}-{diag['max_w']:.2f} (\u03bc={diag['avg_w']:.2f} \u03c3={diag['std_w']:.2f}) phase={phase}")

        if ep in (CURR_W_ONLY_EP, CURR_WB_ONLY_EP):
            snap = np.mean([run_episode_pg_eval(coords, tt, policy, phase=phase) for _ in range(20)])
            tag = "w-only" if ep==CURR_W_ONLY_EP else "w+b"
            print(f"[seed {seed}] end {tag} eval: {snap:.2f}")

        if (ep % EVAL_EVERY) == 0:
            snap_pg = np.mean([run_episode_pg_eval(coords, tt, policy, phase=phase)
                              for _ in range(SNAP_EVAL_EPISODES)])
            snap_evals.append((ep, snap_pg))  # NEW: Save (episode, performance)

            if snap_pg > best_eval:
                best_eval = snap_pg
                best_state = {
                    "policy": {k: v.cpu().clone() for k, v in policy.state_dict().items()},
                    "critic": {k: v.cpu().clone() for k, v in critic.state_dict().items()},
                    "ep": ep,
                    "phase": phase,
                }
            print(f"[train s{seed}] ep={ep:04d} snap_eval={snap_pg:.4f} best={best_eval:.4f}")

    if best_state is not None:
        policy.load_state_dict(best_state["policy"])
        critic.load_state_dict(best_state["critic"])
        print(f"[seed {seed}] restored best snapshot from ep={best_state['ep']} (phase={best_state['phase']}, eval\u2248{best_eval:.2f})")
        best_phase = best_state["phase"]
    else:
        best_phase = phase_for_ep(TRAIN_EPISODES)

    print("Running evaluation for PG-modifier...")
    pg_eval   = np.mean([run_episode_pg_eval(coords,tt,policy, phase=best_phase) for _ in range(EVAL_EPISODES)])
    print("Running evaluation for NoMod baseline...")
    nomod_eval= np.mean([run_episode_nomod(coords,tt) for _ in range(EVAL_EPISODES)])
    print("Running evaluation for Heuristic baseline...")
    heur_eval = np.mean([run_episode_heur(coords,tt) for _ in range(EVAL_EPISODES)])

    Path(outdir).mkdir(exist_ok=True)
    with open(os.path.join(outdir, f"curve_seed{seed}.csv"), "w", newline="") as f:
        w = csv.writer(f); w.writerow(["episode","served"])
        for i,v in enumerate(ep_returns,1): w.writerow([i,v])
    with open(os.path.join(outdir, f"diag_seed{seed}.csv"), "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=[
            "episode","phase","avg_b","gate_frac","avg_dq","neg_w_frac","feas_density","ent",
            "mip_status","mip_runtime","mip_gap","served","avg_queue_size","max_queue_size",
            "avg_w","std_w","min_w","max_w"
        ])
        w.writeheader(); w.writerows(diag_rows)

    return ep_returns, snap_evals, pg_eval, nomod_eval, heur_eval  # NEW: return snap_evals

# ======== BASELINE COMPARISONS ========

def run_episode_nomod(coords,tt):
    """
    No-Modifier Baseline: Standard MILP solver with uniform weights.

    This baseline uses the MILP solver WITHOUT any policy modifications:
    - All requests get equal weight (w=1.0)
    - No deadline tightening (b=0.0)
    - No capacity modifications (\u0394Q=0.0)

    The MILP simply maximizes the number of feasible assignments given the
    original problem constraints. This represents the "greedy feasibility"
    approach: serve as many requests as possible without any learned prioritization.

    Purpose: Shows how well a pure optimization approach works without RL.
    """
    st=make_initial_state(coords,tt); pending=[]; tot=0
    for _ in range(EP_STEPS):
        for _ in range(REQUESTS_PER_EPOCH):
            req=generate_request(st)
            pending.append(req)

        pending=[r for r in pending if r.deadline>=st.t]
        K=len(pending); w=[1.0]*K; dq=[0.0]*len(st.vehicles); b=[0.0]*K  # Uniform weights!
        action,served,_=solve_epoch_milp_modified(st,pending,w,dq,b,TIME_LIMIT_MIP)
        tot+=len(served)

        # Apply ALL vehicle actions
        if action:
            for v_id, route in action.items():
                v = st.vehicles[v_id]
                t = v.time
                node = v.node
                for (i, j) in route:
                    t += st.tt[i, j] + SERVICE_TIME
                    node = j
                v.time = t
                v.node = node

        for idx in sorted(served,reverse=True): pending.pop(idx)
        st.t+=DT
    return tot


def run_episode_heur(coords,tt):
    """
    Greedy Heuristic Baseline: Fast myopic assignment rule.

    This baseline uses a simple greedy heuristic WITHOUT optimization:
    - For each request in queue (in order), find the first available vehicle
      that can serve it feasibly
    - Assign immediately (no look-ahead, no comparison with other requests)
    - First-come-first-served with earliest-completion-time tie-breaking

    This is a fast O(n\u00b7m) heuristic compared to MILP's exponential worst-case.
    It represents what a simple dispatch system without optimization would do.

    Purpose: Shows the value of optimization (MILP vs heuristic) separate from
    the value of learning (PG-modifier vs NoMod).

    Expected ordering: Heur \u2264 NoMod \u2264 PG (if learning works)
    """
    st=make_initial_state(coords,tt); pending=[]; tot=0
    for _ in range(EP_STEPS):
        for _ in range(REQUESTS_PER_EPOCH):
            req=generate_request(st)
            pending.append(req)

        pending=[r for r in pending if r.deadline>=st.t]

        # Simple greedy: assign first feasible request to first available vehicle
        served_indices = []
        for req_idx, req in enumerate(pending):
            best_v = None
            best_time = float('inf')

            for v in st.vehicles:
                if v.time > st.t:  # Vehicle busy
                    continue
                if req.pax > v.capacity:
                    continue

                arr_p = v.time + st.tt[v.node, req.pickup] + SERVICE_TIME
                arr_d = arr_p + st.tt[req.pickup, req.drop] + SERVICE_TIME

                if arr_d <= req.deadline and arr_d < best_time:
                    best_time = arr_d
                    best_v = v

            if best_v:
                # Assign this request to this vehicle (greedy, no backtracking)
                best_v.time = best_time
                best_v.node = req.drop
                served_indices.append(req_idx)

        tot += len(served_indices)
        for idx in sorted(served_indices, reverse=True):
            pending.pop(idx)

        st.t += DT
    return tot


def run_experiment(seed_list=(0,1,2)):
    """
    Run complete experiment: train PG-modifier and compare against baselines.

    For each seed:
    1. Train PG-modifier policy for TRAIN_EPISODES episodes
    2. Evaluate trained policy (deterministic) for EVAL_EPISODES episodes
    3. Evaluate NoMod baseline (MILP with uniform weights) for EVAL_EPISODES episodes
    4. Evaluate Heur baseline (greedy heuristic) for EVAL_EPISODES episodes

    Then aggregate results across seeds and generate plots + summary statistics.
    """
    print("Beginning experiment...")
    curves = []
    snap_eval_curves = []  # NEW: Store snap_eval histories
    rows = []

    for s in seed_list:
        curve, snap_evals, pg, nm, he = train_single_seed(s)
        curves.append(curve)
        snap_eval_curves.append(snap_evals)  # NEW: Store for plotting
        rows.append({"seed":s, "PG":pg, "NoMod":nm, "Heur":he})

    with open(os.path.join(OUTDIR,"summary.csv"),"w",newline="") as f:
        w=csv.DictWriter(f,fieldnames=["seed","PG","NoMod","Heur"])
        w.writeheader(); w.writerows(rows)

    # ========== PLOTTING ==========
    """
    We generate two learning curve plots to visualize training progress:

    PLOT 1: Raw Learning Curve (pg_curve.png)
    - Shows episode-by-episode training performance (noisy)
    - Mean across seeds with \u00b11 std deviation shaded region
    - Horizontal lines show final evaluation performance of baselines
    - Vertical lines mark curriculum phase boundaries (w-only \u2192 w+b \u2192 full)

    PLOT 2: Smoothed Learning Curve (pg_curve_smoothed.png)
    - Same data but with 50-episode moving average
    - Removes high-frequency noise to show learning trends clearly
    - Better for presentations

    PLOT 3: Plot of Evaluation on Snap_Eval (pg_curve_smoothed.png)
    - Fairer comparison between the three models

    Interpretation Guide:
    - If PG curve converges ABOVE NoMod \u2192 Learning useful prioritization
    - If PG curve equals NoMod \u2192 Bottleneck is capacity, not assignment quality
    - If NoMod >> Heur \u2192 Optimization (MILP) provides value
    - If NoMod \u2248 Heur \u2192 Problem is easy, simple heuristics sufficient
    - If PG curve doesn't rise \u2192 Learning rate, features, or reward design issue
    """

    T=len(curves[0])
    mean_curve=[statistics.mean([c[t] for c in curves]) for t in range(T)]
    std_curve =[statistics.pstdev([c[t] for c in curves]) for t in range(T)]

    Path(OUTDIR).mkdir(exist_ok=True)

    # ===== PLOT 1: Raw learning curve =====
    plt.figure(figsize=(10, 6))
    plt.plot(range(1,T+1), mean_curve, label="PG-modifier (mean)", linewidth=2)
    plt.fill_between(range(1,T+1),
                     [m-s for m,s in zip(mean_curve,std_curve)],
                     [m+s for m,s in zip(mean_curve,std_curve)], alpha=0.2)

    # Baseline comparison lines (horizontal at final eval performance)
    plt.axhline(y=np.mean([r['NoMod'] for r in rows]), color='red', linestyle='--',
                label=f"NoMod baseline ({np.mean([r['NoMod'] for r in rows]):.1f})", linewidth=1.5)
    plt.axhline(y=np.mean([r['Heur'] for r in rows]), color='orange', linestyle='--',
                label=f"Heuristic baseline ({np.mean([r['Heur'] for r in rows]):.1f})", linewidth=1.5)

    # Curriculum phase boundaries (vertical lines + labels)
    plt.axvline(x=CURR_W_ONLY_EP, color='gray', linestyle=':', alpha=0.5, linewidth=1)
    plt.axvline(x=CURR_WB_ONLY_EP, color='gray', linestyle=':', alpha=0.5, linewidth=1)
    plt.text(CURR_W_ONLY_EP/2, plt.ylim()[1]*0.95, 'Phase: w-only',
             ha='center', fontsize=9, color='gray')
    plt.text((CURR_W_ONLY_EP+CURR_WB_ONLY_EP)/2, plt.ylim()[1]*0.95, 'Phase: w+b',
             ha='center', fontsize=9, color='gray')
    plt.text((CURR_WB_ONLY_EP+T)/2, plt.ylim()[1]*0.95, 'Phase: full',
             ha='center', fontsize=9, color='gray')

    plt.xlabel("Episode", fontsize=12)
    plt.ylabel("Requests served per episode", fontsize=12)
    plt.legend(loc='lower right', fontsize=10)
    plt.title("Learning Curve: PG Modifier (Raw)", fontsize=14)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()

    plt.savefig(os.path.join(OUTDIR,"pg_curve.png"), dpi=150, bbox_inches="tight")
    plt.savefig(os.path.join(OUTDIR,"pg_curve.svg"), bbox_inches="tight")
    plt.close()

    # ===== PLOT 2: Smoothed learning curve (moving average) =====
    window = 50  # Moving average window size
    plt.figure(figsize=(10, 6))

    # Compute moving average for each seed's curve
    smoothed_curves = []
    for curve in curves:
        smoothed = []
        for i in range(len(curve)):
            start = max(0, i - window + 1)
            smoothed.append(np.mean(curve[start:i+1]))  # Average over [start, i]
        smoothed_curves.append(smoothed)

    # Mean and std of smoothed curves
    mean_smooth = [statistics.mean([c[t] for c in smoothed_curves]) for t in range(T)]
    std_smooth = [statistics.pstdev([c[t] for c in smoothed_curves]) for t in range(T)]

    plt.plot(range(1,T+1), mean_smooth, label="PG-modifier (50-ep moving avg)", linewidth=2)
    plt.fill_between(range(1,T+1),
                     [m-s for m,s in zip(mean_smooth,std_smooth)],
                     [m+s for m,s in zip(mean_smooth,std_smooth)], alpha=0.2)

    plt.axhline(y=np.mean([r['NoMod'] for r in rows]), color='red', linestyle='--',
                label=f"NoMod baseline ({np.mean([r['NoMod'] for r in rows]):.1f})", linewidth=1.5)
    plt.axhline(y=np.mean([r['Heur'] for r in rows]), color='orange', linestyle='--',
                label=f"Heuristic baseline ({np.mean([r['Heur'] for r in rows]):.1f})", linewidth=1.5)

    plt.axvline(x=CURR_W_ONLY_EP, color='gray', linestyle=':', alpha=0.5, linewidth=1)
    plt.axvline(x=CURR_WB_ONLY_EP, color='gray', linestyle=':', alpha=0.5, linewidth=1)

    plt.xlabel("Episode", fontsize=12)
    plt.ylabel("Requests served per episode", fontsize=12)
    plt.legend(loc='lower right', fontsize=10)
    plt.title("Learning Curve: PG Modifier (Smoothed)", fontsize=14)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()

    plt.savefig(os.path.join(OUTDIR,"pg_curve_smoothed.png"), dpi=150, bbox_inches="tight")
    plt.savefig(os.path.join(OUTDIR,"pg_curve_smoothed.svg"), bbox_inches="tight")
    plt.close()

    # ===== PLOT 2: Snap Eval Curve (Evaluation Performance During Training) =====
    plt.figure(figsize=(10, 6))

    # Plot each seed's snap eval curve
    for i, snap_evals in enumerate(snap_eval_curves):
        if snap_evals:  # Check if list is not empty
            episodes, performances = zip(*snap_evals)  # Unpack [(ep1, perf1), (ep2, perf2), ...]
            plt.plot(episodes, performances, alpha=0.3, linewidth=1)

    # Compute mean snap eval performance across seeds
    # First, collect all evaluation points
    all_eval_episodes = sorted(set(ep for snap_evals in snap_eval_curves for ep, _ in snap_evals))

    mean_snap_eval = []
    std_snap_eval = []
    for target_ep in all_eval_episodes:
        # Get performance at this episode from all seeds
        perfs = [perf for snap_evals in snap_eval_curves
                 for ep, perf in snap_evals if ep == target_ep]
        if perfs:
            mean_snap_eval.append(statistics.mean(perfs))
            std_snap_eval.append(statistics.pstdev(perfs) if len(perfs) > 1 else 0)
        else:
            mean_snap_eval.append(float('nan'))
            std_snap_eval.append(float('nan'))

    # Plot mean with error bands
    plt.plot(all_eval_episodes, mean_snap_eval, label="PG-modifier (snap eval)",
             linewidth=2, color='blue')
    plt.fill_between(all_eval_episodes,
                     [m-s for m,s in zip(mean_snap_eval, std_snap_eval)],
                     [m+s for m,s in zip(mean_snap_eval, std_snap_eval)],
                     alpha=0.2, color='blue')

    # Baseline comparison lines
    plt.axhline(y=np.mean([r['NoMod'] for r in rows]), color='red', linestyle='--',
                label=f"NoMod baseline ({np.mean([r['NoMod'] for r in rows]):.1f})", linewidth=1.5)
    plt.axhline(y=np.mean([r['Heur'] for r in rows]), color='orange', linestyle='--',
                label=f"Heuristic baseline ({np.mean([r['Heur'] for r in rows]):.1f})", linewidth=1.5)

    plt.xlabel("Episode", fontsize=12)
    plt.ylabel("Requests served per episode (evaluation)", fontsize=12)
    plt.legend(loc='lower right', fontsize=10)
    plt.title("Snap Eval Performance During Training", fontsize=14)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()

    plt.savefig(os.path.join(OUTDIR,"pg_snap_eval_curve.png"), dpi=150, bbox_inches="tight")
    plt.savefig(os.path.join(OUTDIR,"pg_snap_eval_curve.svg"), bbox_inches="tight")
    plt.show()
    plt.close()

    # ===== Summary statistics =====
    def stats(key):
        vals=[r[key] for r in rows]; return np.mean(vals), np.std(vals)

    for r in rows:
      print(r)  # Print per-seed results

    m_pg,s_pg = stats("PG"); m_nm,s_nm = stats("NoMod"); m_he,s_he = stats("Heur")
    print(f"\nFinal (mean\u00b1std over {len(seed_list)} seeds):")
    print(f"  PG-modifier: {m_pg:.2f} \u00b1 {s_pg:.2f}")
    print(f"  No-Mod     : {m_nm:.2f} \u00b1 {s_nm:.2f}")
    print(f"  Heuristic  : {m_he:.2f} \u00b1 {s_he:.2f}")

if __name__ == "__main__":
    run_experiment(seed_list=(1,2,4,8))
