# -*- coding: utf-8 -*-
"""pg_2nd_phase.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v0q3KOSs0_SmVShy0yiTg2JmhKCFH7gT
"""

!pip uninstall -y torch torchvision torchaudio

!pip install --no-cache-dir torch torchvision torchaudio

import torch
print(torch.__version__)
print(torch.rand(2,3))

!pip -q install gurobipy==11.0.3

import gurobipy as gp
from gurobipy import GRB, GurobiError

WLS_ACCESS_ID = "WLS_ACCESS_ID"
WLS_SECRET = "WLS_SECRET"
LICENSE_ID = LICENSE_ID

GLOBAL_ENV = gp.Env(empty=True)
GLOBAL_ENV.setParam("WLSAccessID", WLS_ACCESS_ID)
GLOBAL_ENV.setParam("WLSSecret", WLS_SECRET)
GLOBAL_ENV.setParam("LICENSEID", LICENSE_ID)
GLOBAL_ENV.start()

import math, random, csv, os, statistics
import numpy as np
from dataclasses import dataclass
from typing import List, Tuple, Dict, Any
from pathlib import Path
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.distributions as D

import gurobipy as gp
from gurobipy import GRB

# ===========================
# Randomness / seeds
# ===========================
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

# ===========================
# RL basics
# ===========================
GAMMA = 0.95
LR = 0.005
GRAD_CLIP = 10.0

# Entropy bonus (small)
ENT0, ENT_DECAY = 0.05, 1.0

# ===========================
# Environment / geometry
# ===========================
DT = 20.0
SERVICE_TIME = 1.0
AREA = 50.0

REQUESTS_PER_EPOCH = 20
N_VEH = 6
VEH_CAP = 4
GRID_SIDE = 20
EP_STEPS = 60

# Candidate generation solves multiple MILPs per step -> keep timelimit modest
TIME_LIMIT_MIP = 0.5

# Training
TRAIN_EPISODES = 2000
EVAL_EPISODES = 50
EVAL_EVERY = 100
SNAP_EVAL_EPISODES = 100

OUTDIR = "report_runs_pg_optionA"

# ===========================
# Types / dataclasses
# ===========================
NodeId = int
Action = Dict[int, List[Tuple[int, int]]]

@dataclass
class Vehicle:
    id: int
    capacity: int
    time: float
    node: NodeId
    load: int = 0

@dataclass
class State:
    T: float
    t: float
    tt: np.ndarray
    coords: List[Tuple[float, float]]
    vehicles: List[Vehicle]

@dataclass
class Request:
    pickup: int
    drop: int
    pax: int
    deadline: float
    base_value: float = 1.0


# ============================================================
# Geometry / demand generation
# ============================================================
def make_grid(n_side: int, area: float):
    coords = []
    step = area / (n_side - 1) if n_side > 1 else 0.0
    for r in range(n_side):
        for c in range(n_side):
            coords.append((r * step, c * step))

    N = n_side * n_side
    tt = np.zeros((N, N), dtype=float)
    for i, (xi, yi) in enumerate(coords):
        for j, (xj, yj) in enumerate(coords):
            tt[i, j] = 0.0 if i == j else math.hypot(xi - xj, yi - yj)
    return coords, tt

def generate_request(state: State, pax_min=1, pax_max=2, slack_low=0.0, slack_high=0.3):
    N = len(state.coords)
    p = random.randrange(N)
    d = random.randrange(N)
    while d == p:
        d = random.randrange(N)

    pax = random.randint(pax_min, pax_max)
    travel = state.tt[p, d]
    deadline = state.t + travel + 2 * SERVICE_TIME + random.uniform(slack_low, slack_high)

    # You can test "learning to prioritize" by making base_value heterogeneous:
    base_value = 1.0
    # base_value = float(pax)
    # base_value = 3.0 if random.random() < 0.1 else 1.0

    return Request(pickup=p, drop=d, pax=pax, deadline=deadline, base_value=base_value)


# ============================================================
# Features (state -> vectors)
# ============================================================
def req_features(state: State, pending: List[Request]):
    feats = []
    for r in pending:
        trip = state.tt[r.pickup, r.drop]
        slack = (r.deadline - state.t) - (trip + 2 * SERVICE_TIME)
        feats.append([trip, r.pax, max(0.0, slack), float(r.pickup), float(r.drop)])
    if not feats:
        feats = [[0, 0, 0, 0, 0]]

    M = max(1, len(state.coords) - 1)
    f = np.array(feats, dtype=np.float32)

    # normalize
    f[:, 0] = f[:, 0] / (AREA * 2 + 1e-6)
    f[:, 1] = f[:, 1] / max(1, VEH_CAP)
    f[:, 2] = f[:, 2] / 5.0
    f[:, 3] = f[:, 3] / M
    f[:, 4] = f[:, 4] / M
    return f

def global_features(state: State, pending: List[Request]):
    rfe = req_features(state, pending)
    slack_stats = [rfe[:, 2].min(), rfe[:, 2].max(), rfe[:, 2].mean()] if len(rfe) > 0 else [0, 0, 0]
    t_phase = (state.t % max(1e-6, state.T)) / max(1e-6, state.T)

    feas_count = 0
    for v in state.vehicles:
        for r in pending:
            arrp = v.time + state.tt[v.node, r.pickup] + SERVICE_TIME
            arrd = arrp + state.tt[r.pickup, r.drop] + SERVICE_TIME
            feas_count += int(arrd <= r.deadline and r.pax <= v.capacity and v.time <= state.t)
    denom = max(1, len(state.vehicles) * max(1, len(pending)))
    feas_density = feas_count / denom

    base = np.array(
        [t_phase, len(pending) / 8.0, slack_stats[0], slack_stats[1], slack_stats[2], feas_density],
        dtype=np.float32
    )

    # extra aggregate stats (helps policy)
    if len(pending) > 0:
        trips = np.array([state.tt[r.pickup, r.drop] for r in pending], dtype=np.float32)
        pax = np.array([r.pax for r in pending], dtype=np.float32)
        slack_raw = np.array([(r.deadline - state.t) - (state.tt[r.pickup, r.drop] + 2 * SERVICE_TIME) for r in pending], dtype=np.float32)
        extras = np.array([
            float(np.mean(trips) / (AREA * 2 + 1e-6)),
            float(np.mean(pax) / max(1, VEH_CAP)),
            float(np.mean(np.clip(slack_raw, 0.0, 5.0)) / 5.0),
        ], dtype=np.float32)
    else:
        extras = np.zeros(3, dtype=np.float32)

    return np.concatenate([base, extras], axis=0)  # dim=9


# ============================================================
# MILP (single epoch)
# ============================================================
def solve_epoch_milp_modified(
    state: State,
    pending: List[Request],
    weights: List[float],
    cap_tighten: List[float],
    deadline_tighten: List[float],
    timelimit=TIME_LIMIT_MIP
):
    V = list(range(len(state.vehicles)))
    K = list(range(len(pending)))

    v_node = [state.vehicles[v].node for v in V]
    v_time = [state.vehicles[v].time for v in V]
    base_cap = [state.vehicles[v].capacity for v in V]
    eff_cap = [max(0.0, base_cap[v] - float(cap_tighten[v])) for v in V]

    eff_dead = []
    for k in K:
        r = pending[k]
        min_time = state.tt[r.pickup, r.drop] + 2 * SERVICE_TIME
        slack = max(0.0, (r.deadline - state.t) - min_time)
        b = min(max(0.0, float(deadline_tighten[k])), slack)
        eff_dead.append(max(state.t, r.deadline - b))

    feas = {(v, k): 1 for v in V for k in K}
    for v in V:
        for k in K:
            r = pending[k]
            if v_time[v] > state.t:
                feas[(v, k)] = 0
                continue
            if r.pax > eff_cap[v]:
                feas[(v, k)] = 0
                continue
            arr_p = v_time[v] + state.tt[v_node[v], r.pickup] + SERVICE_TIME
            arr_d = arr_p + state.tt[r.pickup, r.drop] + SERVICE_TIME
            if arr_d > eff_dead[k]:
                feas[(v, k)] = 0
                continue

    m = gp.Model("epoch_mod", env=GLOBAL_ENV)
    m.Params.OutputFlag = 0
    m.Params.TimeLimit = timelimit
    x = m.addVars(V, K, vtype=GRB.BINARY, name="x")

    for k in K:
        m.addConstr(gp.quicksum(x[v, k] for v in V) <= 1)
    for v in V:
        m.addConstr(gp.quicksum(x[v, k] for k in K) <= 1)

    for v in V:
        for k in K:
            if feas[(v, k)] == 0:
                m.addConstr(x[v, k] == 0)

    m.setObjective(
        gp.quicksum(float(weights[k]) * x[v, k] for v in V for k in K if feas[(v, k)] == 1),
        GRB.MAXIMIZE
    )
    m.optimize()

    status = int(m.Status)
    runtime = float(getattr(m, "Runtime", float("nan")))
    mipgap = float(getattr(m, "MIPGap", float("nan")))
    diag = dict(status=status, runtime=runtime, mipgap=mipgap)

    action: Action = {}
    served_idx = []
    for v in V:
        for k in K:
            if feas[(v, k)] == 1 and x[v, k].X > 0.5:
                req = pending[k]
                action[v] = [(state.vehicles[v].node, req.pickup), (req.pickup, req.drop)]
                served_idx.append(k)

    return action, served_idx, diag


# ============================================================
# Sim step
# ============================================================
def apply_action_and_advance(state: State, pending: List[Request], action: Action, served: List[int]):
    if action:
        for v_id, route in action.items():
            v = state.vehicles[v_id]
            t = v.time
            node = v.node
            for (i, j) in route:
                t += state.tt[i, j] + SERVICE_TIME
                node = j
            v.time = t
            v.node = node

    for idx in sorted(served, reverse=True):
        pending.pop(idx)

    state.t += DT


def make_initial_state(coords, tt, n_vehicles=N_VEH):
    vehicles = []
    N = len(coords)
    for i in range(n_vehicles):
        if i == 0:
            node = 0
        elif i == 1:
            node = N - 1
        else:
            node = int((i / n_vehicles) * N)
        vehicles.append(Vehicle(id=i, capacity=VEH_CAP, time=0.0, node=node))
    return State(T=10.0, t=0.0, tt=tt, coords=coords, vehicles=vehicles)


# ============================================================
# Candidate modes (small discrete action space)
# ============================================================
def build_candidate_modes() -> List[Dict[str, Any]]:
    modes = []

    def mode_nomod(state, pending):
        K = len(pending)
        V = len(state.vehicles)
        return [1.0]*K, [0.0]*K, [0.0]*V

    def mode_urgency(state, pending):
        V = len(state.vehicles)
        w = []
        for r in pending:
            trip = state.tt[r.pickup, r.drop]
            slack = (r.deadline - state.t) - (trip + 2*SERVICE_TIME)
            w.append(float(1.0 + 3.0*np.exp(-max(0.0, slack))))
        return w, [0.0]*len(pending), [0.0]*V

    def mode_shorttrip(state, pending):
        V = len(state.vehicles)
        w = []
        for r in pending:
            trip = state.tt[r.pickup, r.drop]
            w.append(float(1.0 + 3.0*(1.0/(1.0+trip))))
        return w, [0.0]*len(pending), [0.0]*V

    def mode_highpax(state, pending):
        V = len(state.vehicles)
        w = [float(1.0 + 2.0*r.pax) for r in pending]
        return w, [0.0]*len(pending), [0.0]*V

    def mode_deadline_buffer(state, pending):
        V = len(state.vehicles)
        w = [1.0]*len(pending)
        b = []
        for r in pending:
            trip = state.tt[r.pickup, r.drop]
            slack = (r.deadline - state.t) - (trip + 2*SERVICE_TIME)
            b.append(float(0.15 if slack > 0.2 else 0.0))
        return w, b, [0.0]*V

    def mode_random(state, pending):
        V = len(state.vehicles)
        w = [float(0.5 + 4.5*random.random()) for _ in pending]
        return w, [0.0]*len(pending), [0.0]*V

    modes.append({"name":"NoMod", "fn": mode_nomod})
    modes.append({"name":"Urgency", "fn": mode_urgency})
    modes.append({"name":"ShortTrip", "fn": mode_shorttrip})
    modes.append({"name":"HighPax", "fn": mode_highpax})
    modes.append({"name":"DeadlineBuf", "fn": mode_deadline_buffer})
    modes.append({"name":"Random", "fn": mode_random})
    return modes

CANDIDATE_MODES = build_candidate_modes()
N_MODES = len(CANDIDATE_MODES)

def generate_candidates(state: State, pending: List[Request], timelimit=TIME_LIMIT_MIP):
    cands = []
    for i, m in enumerate(CANDIDATE_MODES):
        w, b, dq = m["fn"](state, pending)
        action, served, diag = solve_epoch_milp_modified(state, pending, w, dq, b, timelimit=timelimit)
        r = sum(pending[k].base_value for k in served) if served else 0.0
        cands.append({
            "mode_id": i,
            "name": m["name"],
            "action": action,
            "served": served,
            "reward": float(r),
            "diag": diag
        })
    return cands


# ============================================================
# Policy: choose among N_MODES (discrete actions)
# ============================================================
class CandidatePolicyNet(nn.Module):
    def __init__(self, d_in=9, h=64, n_actions=N_MODES):
        super().__init__()
        print("Loading candidate-policy (Option A)...")
        self.net = nn.Sequential(
            nn.Linear(d_in, h),
            nn.ReLU(),
            nn.Linear(h, h),
            nn.ReLU(),
            nn.Linear(h, n_actions),
        )
        with torch.no_grad():
            for m in self.modules():
                if isinstance(m, nn.Linear):
                    nn.init.orthogonal_(m.weight, gain=0.7)
                    if m.bias is not None:
                        nn.init.zeros_(m.bias)

    def logits(self, g):
        return self.net(g)

    def sample(self, g):
        dist = D.Categorical(logits=self.logits(g))
        a = dist.sample()
        return int(a.item()), dist.log_prob(a), dist.entropy()

    def deterministic(self, g):
        return int(torch.argmax(self.logits(g)).item())

class Critic(nn.Module):
    def __init__(self, d_in=9, h=64):
        super().__init__()
        print("Loading critic...")
        self.net = nn.Sequential(nn.Linear(d_in,h), nn.ReLU(), nn.Linear(h,1))
    def forward(self, g):
        return self.net(g).squeeze(-1)


# ============================================================
# Rollout (train)
# ============================================================
def run_episode_optionA(coords, tt, policy: CandidatePolicyNet, critic: Critic, ent_coef=0.0, debug=False):
    st = make_initial_state(coords, tt)
    pending: List[Request] = []

    logps, ents, rewards, gbuf = [], [], [], []
    served_counts = []
    chosen_modes = []

    for step in range(EP_STEPS):
        for _ in range(REQUESTS_PER_EPOCH):
            pending.append(generate_request(st))
        pending = [r for r in pending if r.deadline >= st.t]

        g = torch.tensor(global_features(st, pending), dtype=torch.float32)

        # candidates via MILP search
        cands = generate_candidates(st, pending)

        # policy chooses a candidate
        a, logp, ent = policy.sample(g)
        chosen = cands[a]

        if debug:
            print(f"[step {step}] pending={len(pending)} choose={chosen['name']} served={len(chosen['served'])} r={chosen['reward']:.1f}")

        # execute chosen action
        apply_action_and_advance(st, pending, chosen["action"], chosen["served"])

        logps.append(logp)
        ents.append(ent)
        rewards.append(torch.tensor(chosen["reward"], dtype=torch.float32))
        gbuf.append(g)
        served_counts.append(len(chosen["served"]))
        chosen_modes.append(a)

    # returns
    G = []
    acc = 0.0
    for r in reversed(rewards):
        acc = r.item() + GAMMA * acc
        G.append(acc)
    G = list(reversed(G))
    G_t = torch.tensor(G, dtype=torch.float32)

    gstack = torch.stack(gbuf)

    with torch.no_grad():
        baseline = critic(gstack)
    adv = G_t - baseline
    adv = (adv - adv.mean()) / (adv.std() + 1e-6)

    diag = {
        "served_total": int(sum(served_counts)),
        "avg_reward": float(torch.mean(torch.stack(rewards)).item()),
        "mode_hist": {CANDIDATE_MODES[i]["name"]: int(sum(1 for x in chosen_modes if x == i)) for i in range(N_MODES)}
    }

    return G_t, adv.detach(), torch.stack(logps), torch.stack(ents), gstack, diag


# ============================================================
# Eval (deterministic policy)
# ============================================================
def run_episode_optionA_eval(coords, tt, policy: CandidatePolicyNet):
    st = make_initial_state(coords, tt)
    pending: List[Request] = []
    total_served = 0

    for _ in range(EP_STEPS):
        for _ in range(REQUESTS_PER_EPOCH):
            pending.append(generate_request(st))
        pending = [r for r in pending if r.deadline >= st.t]

        g = torch.tensor(global_features(st, pending), dtype=torch.float32)
        a = policy.deterministic(g)

        cands = generate_candidates(st, pending)
        chosen = cands[a]
        total_served += len(chosen["served"])
        apply_action_and_advance(st, pending, chosen["action"], chosen["served"])

    return total_served


# ============================================================
# Baselines
# ============================================================
def run_episode_nomod(coords, tt):
    st = make_initial_state(coords, tt)
    pending: List[Request] = []
    tot = 0
    for _ in range(EP_STEPS):
        for _ in range(REQUESTS_PER_EPOCH):
            pending.append(generate_request(st))
        pending = [r for r in pending if r.deadline >= st.t]
        K = len(pending); V = len(st.vehicles)
        w = [1.0]*K; b = [0.0]*K; dq = [0.0]*V
        action, served, _ = solve_epoch_milp_modified(st, pending, w, dq, b, TIME_LIMIT_MIP)
        tot += len(served)
        apply_action_and_advance(st, pending, action, served)
    return tot

def run_episode_heur(coords, tt):
    st = make_initial_state(coords, tt)
    pending: List[Request] = []
    tot = 0
    for _ in range(EP_STEPS):
        for _ in range(REQUESTS_PER_EPOCH):
            pending.append(generate_request(st))
        pending = [r for r in pending if r.deadline >= st.t]

        served_indices = []
        used = set()
        for req_idx, req in enumerate(pending):
            best_v = None
            best_time = float("inf")
            for v in st.vehicles:
                if v.id in used:
                    continue
                if v.time > st.t:
                    continue
                if req.pax > v.capacity:
                    continue
                arr_p = v.time + st.tt[v.node, req.pickup] + SERVICE_TIME
                arr_d = arr_p + st.tt[req.pickup, req.drop] + SERVICE_TIME
                if arr_d <= req.deadline and arr_d < best_time:
                    best_time = arr_d
                    best_v = v
            if best_v is not None:
                best_v.time = best_time
                best_v.node = req.drop
                used.add(best_v.id)
                served_indices.append(req_idx)

        tot += len(served_indices)
        for idx in sorted(served_indices, reverse=True):
            pending.pop(idx)
        st.t += DT
    return tot


# ============================================================
# Training
# ============================================================
def train_single_seed(seed: int, outdir=OUTDIR, log_curve=True):
    random.seed(seed); np.random.seed(seed); torch.manual_seed(seed)

    coords, tt = make_grid(GRID_SIDE, AREA)
    policy = CandidatePolicyNet(d_in=9, h=64, n_actions=N_MODES)
    critic = Critic(d_in=9, h=64)

    opt_p = torch.optim.Adam(policy.parameters(), lr=LR)
    opt_c = torch.optim.Adam(critic.parameters(), lr=LR)

    ent_coef = ENT0
    ep_served = []
    snap_evals = []
    best_eval = -1e9
    best_state = None
    diag_rows = []

    for ep in range(1, TRAIN_EPISODES + 1):
        G_t, adv, logps, ents, gstack, diag = run_episode_optionA(coords, tt, policy, critic, ent_coef=ent_coef, debug=False)
        ep_served.append(diag["served_total"])

        # critic update
        pred = critic(gstack)
        v_loss = F.mse_loss(pred, G_t.detach())
        opt_c.zero_grad()
        v_loss.backward()
        nn.utils.clip_grad_norm_(critic.parameters(), GRAD_CLIP)
        opt_c.step()

        # policy update
        pg_loss = -(adv * logps).sum() - ent_coef * ents.sum()
        opt_p.zero_grad()
        pg_loss.backward()
        nn.utils.clip_grad_norm_(policy.parameters(), GRAD_CLIP)
        opt_p.step()

        ent_coef *= ENT_DECAY

        diag_rows.append({
            "episode": ep,
            "served": diag["served_total"],
            "avg_reward": diag["avg_reward"],
            **{f"mode_{k}": v for k, v in diag["mode_hist"].items()}
        })

        if log_curve and (ep % 100) == 0:
            mh = ", ".join([f"{k}:{v}" for k, v in diag["mode_hist"].items()])
            print(f"[train s{seed}] ep={ep:04d} served={diag['served_total']:4d} avgR={diag['avg_reward']:.2f} modes({mh})")

        if (ep % EVAL_EVERY) == 0:
            snap = float(np.mean([run_episode_optionA_eval(coords, tt, policy) for _ in range(SNAP_EVAL_EPISODES)]))
            snap_evals.append((ep, snap))
            if snap > best_eval:
                best_eval = snap
                best_state = {k: v.cpu().clone() for k, v in policy.state_dict().items()}
            print(f"[train s{seed}] ep={ep:04d} snap_eval={snap:.2f} best={best_eval:.2f}")

    if best_state is not None:
        policy.load_state_dict(best_state)
        print(f"[seed {seed}] restored best snapshot eval≈{best_eval:.2f}")

    pg_eval = float(np.mean([run_episode_optionA_eval(coords, tt, policy) for _ in range(EVAL_EPISODES)]))
    nomod_eval = float(np.mean([run_episode_nomod(coords, tt) for _ in range(EVAL_EPISODES)]))
    heur_eval = float(np.mean([run_episode_heur(coords, tt) for _ in range(EVAL_EPISODES)]))

    Path(outdir).mkdir(exist_ok=True)

    with open(os.path.join(outdir, f"curve_seed{seed}.csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["episode", "served"])
        for i, v in enumerate(ep_served, 1):
            w.writerow([i, v])

    with open(os.path.join(outdir, f"diag_seed{seed}.csv"), "w", newline="") as f:
        cols = list(diag_rows[0].keys()) if diag_rows else ["episode", "served", "avg_reward"]
        w = csv.DictWriter(f, fieldnames=cols)
        w.writeheader()
        w.writerows(diag_rows)

    return ep_served, snap_evals, pg_eval, nomod_eval, heur_eval


def run_experiment(seed_list=(1,2,4,8)):
    curves = []
    snap_eval_curves = []
    rows = []

    for s in seed_list:
        curve, snap_evals, pg, nm, he = train_single_seed(s)
        curves.append(curve)
        snap_eval_curves.append(snap_evals)
        rows.append({"seed": s, "PG_OptionA": pg, "NoMod": nm, "Heur": he})

    Path(OUTDIR).mkdir(exist_ok=True)
    with open(os.path.join(OUTDIR, "summary.csv"), "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["seed", "PG_OptionA", "NoMod", "Heur"])
        w.writeheader()
        w.writerows(rows)

    # Learning curve plot
    T = len(curves[0])
    mean_curve = [statistics.mean([c[t] for c in curves]) for t in range(T)]
    std_curve = [statistics.pstdev([c[t] for c in curves]) for t in range(T)]

    plt.figure(figsize=(10, 6))
    plt.plot(range(1, T + 1), mean_curve, label="PG OptionA (mean)", linewidth=2)
    plt.fill_between(
        range(1, T + 1),
        [m - s for m, s in zip(mean_curve, std_curve)],
        [m + s for m, s in zip(mean_curve, std_curve)],
        alpha=0.2
    )
    plt.axhline(y=np.mean([r["NoMod"] for r in rows]), linestyle="--",
                label=f"NoMod ({np.mean([r['NoMod'] for r in rows]):.1f})")
    plt.axhline(y=np.mean([r["Heur"] for r in rows]), linestyle="--",
                label=f"Heur ({np.mean([r['Heur'] for r in rows]):.1f})")
    plt.xlabel("Episode")
    plt.ylabel("Requests served (training)")
    plt.title("Learning Curve: PG Option A (policy chooses candidate MILP action)")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(OUTDIR, "pg_optionA_curve.png"), dpi=150, bbox_inches="tight")
    plt.close()

    # Snap eval plot
    plt.figure(figsize=(10, 6))
    for snap_evals in snap_eval_curves:
        if snap_evals:
            x, y = zip(*snap_evals)
            plt.plot(x, y, alpha=0.35)

    all_eps = sorted(set(ep for snap_evals in snap_eval_curves for ep, _ in snap_evals))
    mean_y = []
    std_y = []
    for e in all_eps:
        vals = [val for snap_evals in snap_eval_curves for ep, val in snap_evals if ep == e]
        mean_y.append(float(np.mean(vals)))
        std_y.append(float(np.std(vals)) if len(vals) > 1 else 0.0)

    plt.plot(all_eps, mean_y, linewidth=2, label="PG OptionA (mean snap eval)")
    plt.fill_between(all_eps, [m - s for m, s in zip(mean_y, std_y)], [m + s for m, s in zip(mean_y, std_y)], alpha=0.2)

    plt.axhline(y=np.mean([r["NoMod"] for r in rows]), linestyle="--",
                label=f"NoMod ({np.mean([r['NoMod'] for r in rows]):.1f})")
    plt.axhline(y=np.mean([r["Heur"] for r in rows]), linestyle="--",
                label=f"Heur ({np.mean([r['Heur'] for r in rows]):.1f})")
    plt.xlabel("Episode")
    plt.ylabel("Requests served (evaluation)")
    plt.title("Snap Eval During Training: PG Option A")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.savefig(os.path.join(OUTDIR, "pg_optionA_snap_eval.png"), dpi=150, bbox_inches="tight")
    plt.close()

    # Summary
    print("\nPer-seed results:")
    for r in rows:
        print(r)

    m_pg = float(np.mean([r["PG_OptionA"] for r in rows])); s_pg = float(np.std([r["PG_OptionA"] for r in rows]))
    m_nm = float(np.mean([r["NoMod"] for r in rows])); s_nm = float(np.std([r["NoMod"] for r in rows]))
    m_he = float(np.mean([r["Heur"] for r in rows])); s_he = float(np.std([r["Heur"] for r in rows]))

    print(f"\nFinal (mean±std over {len(seed_list)} seeds):")
    print(f"  PG OptionA: {m_pg:.2f} ± {s_pg:.2f}")
    print(f"  NoMod     : {m_nm:.2f} ± {s_nm:.2f}")
    print(f"  Heuristic : {m_he:.2f} ± {s_he:.2f}")


if __name__ == "__main__":
    run_experiment(seed_list=(1,2,4,8))

print("ping")
