# -*- coding: utf-8 -*-
"""vfa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nZ8D-tuM4y3Q3zD4cZSHkfdjldpA2lvJ
"""

import gurobipy as gp
from gurobipy import GRB, GurobiError

WLS_ACCESS_ID = "WLS_ACCESS_ID"
WLS_SECRET = "WLS_SECRET"
LICENSE_ID = LICENSE_ID

GLOBAL_ENV = gp.Env(empty=True)
GLOBAL_ENV.setParam("WLSAccessID", "----")
GLOBAL_ENV.setParam("WLSSecret", "----")
GLOBAL_ENV.setParam("LICENSEID", LICENSE_ID)
GLOBAL_ENV.start()

_test = gp.Model("license_check", env=GLOBAL_ENV)
_test.optimize()

import random
from dataclasses import dataclass
from typing import List, Tuple, Dict
from math import hypot
import numpy as np
import torch
import torch.nn as nn
import gurobipy as gp
from gurobipy import GRB, GurobiError
from statistics import mean, stdev

# --- knobs---
RANDOM_SEED   = 42
RELU_HIDDEN   = 2
W_BOUND       = 10.0        # upper bound on neural network weights
W_BOUND_JOINT = 3.0         #tighter bound just for joint-k trainer
TRAIN_SAMPLES = 600         # example scenarios to train neural network (used by heuristic-target trainer)
ROLLOUT_H     = 10
GAMMA         = 0.95        # discount factor
LAMBDA_VFA    = 0.25
LAMBDA_VFA_JOINT = 1.6
CALIB_TARGET  = 0.7         # target value for calibrating nn-outputs
TLIM_TRAIN    = 60.0        # time-limit for training (seconds)
TLIM_PLAN     = 5.0         # time-limit for planning each decision (seconds)
TRAIN_LIMITS  = [160, 120, 96, 80, 60, 40, 24, 16]  # different training set sizes to try
JOINT_K       = 6           # small horizon for joint trainer
JOINT_GRID_SIDE = 3         # dummy-point grid for joint trainer
MAX_PENDING   = 6           # cap on pending queue to keep MILP small
DEMAND_MULT = 0.25           #1.0 = baseline, <1 = higher load, >1 = lower load
BASE_SLACK_LOW = 0.5
BASE_SLACK_HIGH = 2.0
N_VEHICLES = 15

random.seed(RANDOM_SEED); np.random.seed(RANDOM_SEED); torch.manual_seed(RANDOM_SEED)

# Creating a quiet Gurobi env
GLOBAL_ENV = gp.Env(empty=True)
GLOBAL_ENV.setParam('OutputFlag', 0)
GLOBAL_ENV.start()

# ---------- data ----------
NodeId = int
Action = Dict[int, List[Tuple[int, int]]]

@dataclass
class Vehicle:
    id: int
    capacity: int
    time: float     # absolute time
    node: NodeId
    load: int = 0

@dataclass
class State:
    T: float        # normalization scale (window)
    t: float        # absolute current time
    tt: np.ndarray
    coords: List[Tuple[float, float]]
    vehicles: List[Vehicle]

@dataclass
class Request:
    pickup: int
    drop: int
    pax: int
    deadline: float   # absolute deadline

def make_initial_vehicles(coords):
    """
    Create the initial list of vehicles given the grid coordinates.
    Change this if you want more/different starting locations.
    """
    if N_VEHICLES == 2:
        return [
            Vehicle(0, 2, 0.0, 0),
            Vehicle(1, 2, 0.0, len(coords) - 1),
        ]
    elif N_VEHICLES == 3:
        # 3 vehicles: top-left, center, bottom-right on 3x3 grid (indices 0..8)
        center = len(coords) // 2  # should be 4 on 3x3
        return [
            Vehicle(0, 2, 0.0, 0),
            Vehicle(1, 2, 0.0, center),
            Vehicle(2, 2, 0.0, len(coords) - 1),
        ]
    else:
        # simple spread along the grid indices
        vehicles = []
        n_nodes = len(coords)
        for vid in range(N_VEHICLES):
            node = int(vid * (n_nodes - 1) / max(1, N_VEHICLES - 1))
            vehicles.append(Vehicle(vid, 2, 0.0, node))
        return vehicles

# ---------- geometry ----------
def make_grid(n_side: int, area: float):
    coords = []
    step = area / (n_side - 1) if n_side > 1 else 0.0
    for r in range(n_side):
        for c in range(n_side):
            coords.append((r*step, c*step))
    N = n_side * n_side
    tt = np.zeros((N, N), dtype=float)
    for i, (xi, yi) in enumerate(coords):
        for j, (xj, yj) in enumerate(coords):
            tt[i, j] = 0.0 if i == j else ((xi - xj)**2 + (yi - yj)**2) ** 0.5
    return coords, tt

def make_dummy_points(k_side: int, area: float):
    pts = []
    step = area / (k_side + 1)
    for r in range(1, k_side + 1):
        for c in range(1, k_side + 1):
            pts.append((r*step, c*step))
    return pts

# ---------- helpers ----------
def _dist_node_to_point(coords, j: NodeId, pt: Tuple[float, float]) -> float:
    xj, yj = coords[j]; x, y = pt
    return hypot(xj - x, yj - y)

# ---------- requests ----------
def generate_request(state: State, pax_min=1, pax_max=2, slack_low=0.5, slack_high=2.0, service_time=1.0) -> Request:
    N = len(state.coords)
    p = random.randrange(N); d = random.randrange(N)
    while d == p: d = random.randrange(N)
    pax = random.randint(pax_min, pax_max)
    travel_pd = state.tt[p, d]
    deadline = state.t + travel_pd + 2*service_time + random.uniform(slack_low, slack_high)  # absolute
    return Request(pickup=p, drop=d, pax=pax, deadline=deadline)

def enumerate_actions(state: State, req: Request, service_time: float = 1.0) -> List[Action]:
    cands = [{}]
    for v in state.vehicles:
        if v.load + req.pax > v.capacity: continue
        arr_pick = v.time + state.tt[v.node, req.pickup] + service_time
        arr_drop = arr_pick + state.tt[req.pickup, req.drop] + service_time
        if arr_drop <= req.deadline:
            cands.append({v.id: [(v.node, req.pickup), (req.pickup, req.drop)]})
    return cands              # return all feasible actions

def immediate_reward(a: Action) -> float:
    return 0.0 if not a else 1.0

def apply_action(state: State, req: Request, a: Action, service_time=1.0):
    if not a: return state
    (v_id, route) = next(iter(a.items()))
    v = next(vh for vh in state.vehicles if vh.id == v_id)
    t = v.time; node = v.node
    for (i, j) in route:
        t += state.tt[i, j] + service_time; node = j
    v.time = t; v.node = node
    return state

# ---------- residual-time features (post-decision) ----------
def finish_times_and_last_nodes(state: State, action: Action, service_time: float = 1.0):
    B_v = []; last_nodes = []
    for v in state.vehicles:
        t = v.time; node = v.node
        for (i, j) in action.get(v.id, []):
            t += state.tt[i, j] + service_time; node = j
        B_v.append(t); last_nodes.append(node)
    return np.array(B_v, dtype=float), last_nodes

def response_time_RT_abs(state: State, B_v: np.ndarray, last_nodes: List[NodeId], dummy_points: List[Tuple[float, float]]) -> float:
    worst = 0.0
    for pt in dummy_points:
        best_here = min(B_v[idx] + _dist_node_to_point(state.coords, last_nodes[idx], pt) for idx in range(len(B_v)))
        worst = max(worst, best_here)
    return worst  # absolute time of worst coverage

def aggregate_features_residual(state: State, action: Action, dummy_points: List[Tuple[float, float]], service_time: float = 1.0):
    T = max(state.T, 1e-6)
    B_v_abs, last_nodes = finish_times_and_last_nodes(state, action, service_time)
    if len(B_v_abs) == 0:
        Bmin_res = Bmax_res = Bbar_res = RT_res = 0.0
    else:
        B_res = np.maximum(0.0, B_v_abs - state.t)
        Bmin_res = float(B_res.min()); Bmax_res = float(B_res.max()); Bbar_res = float(B_res.mean())
        RT_abs = response_time_RT_abs(state, B_v_abs, last_nodes, dummy_points)
        RT_res = max(0.0, RT_abs - state.t)
    bmin_n = min(1.0, Bmin_res / T)
    bmax_n = min(1.0, Bmax_res / T)
    bbar_n = min(1.0, Bbar_res / T)
    rt_n   = min(1.0, RT_res   / T)
    t_phase = (state.t % T) / T
    z = np.array([t_phase, bmin_n, bmax_n, bbar_n, rt_n], dtype=np.float32)
    return z, Bmin_res, Bmax_res, Bbar_res, RT_res

# ---------- tiny heuristic (targets only) ----------
def pick_best_action_heur(state: State, req: Request, P, service_time=1.0):
    best_a = {}; best_s, best_rt = -1e9, 1e9
    for a in enumerate_actions(state, req, service_time):
        s = immediate_reward(a)
        _, _, _, _, RT_res = aggregate_features_residual(state, a, P, service_time)
        if (s > best_s) or (s == best_s and RT_res < best_rt):
            best_a, best_s, best_rt = a, s, RT_res
    return best_a, best_s

# ---------- ReLU VFA ----------
class ReLUVFA:
    def __init__(self, hidden=RELU_HIDDEN, device="cpu"):
        self.model = nn.Sequential(nn.Linear(5, hidden), nn.ReLU(), nn.Linear(hidden, 1)).to(device)
        with torch.no_grad():
            for p in self.model.parameters(): p.zero_()

    def predict(self, x: np.ndarray) -> float:
        with torch.no_grad():
            t = torch.tensor(x, dtype=torch.float32).unsqueeze(0)
            return float(self.model(t).squeeze())

def extract_relu_weights(m: "ReLUVFA"):
    l1, _, l2 = m.model
    W1 = l1.weight.detach().cpu().numpy()
    b1 = l1.bias.detach().cpu().numpy()
    W2 = l2.weight.detach().cpu().numpy()
    b2 = l2.bias.detach().cpu().numpy()
    return W1, b1, W2.reshape(-1), float(b2.item())

# ---------- MILP helpers ----------
def add_min_over(m, vals, M, name):
    n = len(vals)
    r = m.addVar(lb=-GRB.INFINITY, name=f"{name}_min")
    z = m.addVars(n, vtype=GRB.BINARY, name=f"{name}_zmin")
    for i in range(n):
        m.addConstr(r <= vals[i], name=f"{name}_min_le_{i}")
        m.addConstr(r >= vals[i] - M*(1 - z[i]), name=f"{name}_min_ge_{i}")
    m.addConstr(gp.quicksum(z[i] for i in range(n)) == 1, name=f"{name}_pick1")
    return r

def add_max_over(m, vals, M, name):
    n = len(vals)
    r = m.addVar(lb=-GRB.INFINITY, name=f"{name}_max")
    z = m.addVars(n, vtype=GRB.BINARY, name=f"{name}_zmax")
    for i in range(n):
        m.addConstr(r >= vals[i], name=f"{name}_max_ge_{i}")
        m.addConstr(r <= vals[i] + M*(1 - z[i]), name=f"{name}_max_le_{i}")
    m.addConstr(gp.quicksum(z[i] for i in range(n)) == 1, name=f"{name}_pick1")
    return r

def bounds_affine_row(w_row: np.ndarray, b: float, xL: np.ndarray, xU: np.ndarray):
    lo = b; hi = b
    for wj, lj, uj in zip(w_row, xL, xU):
        if wj >= 0: lo += wj * lj; hi += wj * uj
        else:       lo += wj * uj; hi += wj * lj
    return lo, hi

def add_relu_block_34_38(m, x_vars, W1, b1, W2, b2, xL, xU, name="vfa"):
    d = len(x_vars); h = W1.shape[0]
    s = m.addVars(h, lb=-GRB.INFINITY, name=f"{name}_s")
    y = m.addVars(h, lb=0.0, name=f"{name}_y")
    z = m.addVars(h, vtype=GRB.BINARY, name=f"{name}_z")
    for j in range(h):
        L, U = bounds_affine_row(W1[j], b1[j], np.array(xL), np.array(xU))
        if U < L: L, U = U, L
        if abs(U - L) < 1e-6: U += 1e-6
        m.addConstr(s[j] == gp.quicksum(float(W1[j,i]) * x_vars[i] for i in range(d)) + float(b1[j]), name=f"{name}_aff_{j}")  # (34)
        m.addConstr(y[j] >= s[j],                name=f"{name}_y_ge_s_{j}")                                                   # (35)
        m.addConstr(y[j] <= s[j] - L*(1 - z[j]), name=f"{name}_relu_on_{j}")                                                   # (36)
        m.addConstr(y[j] <= U * z[j],            name=f"{name}_relu_off_{j}")                                                  # (37)
    vhat = m.addVar(lb=-GRB.INFINITY, name=f"{name}_out")
    m.addConstr(vhat == gp.quicksum(float(W2[j]) * y[j] for j in range(h)) + float(b2), name=f"{name}_out_def")               # (38)
    return vhat

# ---------- Full MILP per epoch ----------
def plan_epoch_with_relu_vfa(state: State, pending: List[Request], P_dummy: List[Tuple[float,float]],
                             relu_model: ReLUVFA, lambda_vfa=LAMBDA_VFA, vfa_scale=1.0,
                             service_time=1.0, timelimit=TLIM_PLAN):
    Vset = list(range(len(state.vehicles)))
    Kset = list(range(len(pending)))
    T = max(state.T, 1e-6); tt = state.tt
    v_node = [state.vehicles[v].node for v in Vset]
    v_time = [state.vehicles[v].time for v in Vset]
    v_cap  = [state.vehicles[v].capacity for v in Vset]

    feas = {(v,k): 1 for v in Vset for k in Kset}
    travel_v_k = {}
    for v in Vset:
        for k in Kset:
            r = pending[k]
            if r.pax > v_cap[v]: feas[(v,k)] = 0; continue
            arr_pick = v_time[v] + tt[v_node[v], r.pickup] + service_time
            arr_drop = arr_pick + tt[r.pickup, r.drop] + service_time
            if arr_drop > r.deadline: feas[(v,k)] = 0; continue
            travel_v_k[(v,k)] = tt[v_node[v], r.pickup] + service_time + tt[r.pickup, r.drop] + service_time

    M = float(T + (np.max(tt) if tt.size else 0.0) + 100.0)
    m = gp.Model("epoch_vfa", env=GLOBAL_ENV)
    m.Params.OutputFlag = 0; m.Params.TimeLimit = timelimit
    m.Params.MIPFocus = 1; m.Params.Heuristics = 0.2

    x = m.addVars(Vset, Kset, vtype=GRB.BINARY, name="x")
    for k in Kset: m.addConstr(gp.quicksum(x[v,k] for v in Vset) <= 1, name=f"c4_{k}")
    for v in Vset: m.addConstr(gp.quicksum(x[v,k] for k in Kset) <= 1, name=f"c12_{v}")

    B_v = m.addVars(Vset, lb=0.0, vtype=GRB.CONTINUOUS, name="B_v")
    for v in Vset:
        m.addConstr(
            B_v[v] == v_time[v] + gp.quicksum(travel_v_k[(v,k)] * x[v,k] for k in Kset if (v,k) in travel_v_k),
            name=f"c7_{v}"
        )
        m.addConstr(gp.quicksum(pending[k].pax * x[v,k] for k in Kset) <= v_cap[v], name=f"c11_{v}")
    for v in Vset:
        for k in Kset:
            if feas[(v,k)] == 0:
                m.addConstr(x[v,k] == 0, name=f"infeas_{v}_{k}")

    R_v = m.addVars(Vset, lb=0.0, name="R_v")
    for v in Vset:
        m.addConstr(R_v[v] >= B_v[v] - state.t, name=f"res_{v}")
    B_minus = add_min_over(m, [R_v[v] for v in Vset], M, name="Bminus")
    B_plus  = add_max_over(m, [R_v[v] for v in Vset], M, name="Bplus")
    B_bar   = m.addVar(lb=0.0, vtype=GRB.CONTINUOUS, name="Bbar")
    if len(Vset) > 0:
        m.addConstr(B_bar == (1.0/len(Vset)) * gp.quicksum(R_v[v] for v in Vset), name="Bbar_def")

    dist_idle = [[_dist_node_to_point(state.coords, v_node[v], P_dummy[i]) for i in range(len(P_dummy))] for v in Vset]
    r_iv_abs = {}
    for i in range(len(P_dummy)):
        for v in Vset:
            d_switch = dist_idle[v][i] + gp.quicksum(
                x[v,k] * (_dist_node_to_point(state.coords, pending[k].drop, P_dummy[i]) - dist_idle[v][i])
                for k in Kset
            )
            r_iv_abs[(i,v)] = m.addVar(lb=0.0, vtype=GRB.CONTINUOUS, name=f"rabs_{i}_{v}")
            m.addConstr(r_iv_abs[(i,v)] == B_v[v] + d_switch, name=f"rabs_def_{i}_{v}")

    r_i_abs = {}; z_iv = {}
    for i in range(len(P_dummy)):
        r_i_abs[i] = m.addVar(lb=0.0, vtype=GRB.CONTINUOUS, name=f"ri_abs_{i}")
        for v in Vset:
            z_iv[(i,v)] = m.addVar(vtype=GRB.BINARY, name=f"z_{i}_{v}")
            m.addConstr(r_i_abs[i] <= r_iv_abs[(i,v)], name=f"rt_le_{i}_{v}")
            m.addConstr(r_i_abs[i] >= r_iv_abs[(i,v)] - M*(1 - z_iv[(i,v)]), name=f"rt_ge_{i}_{v}")
        m.addConstr(gp.quicksum(z_iv[(i,v)] for v in Vset) == 1, name=f"pickmin_{i}")
    RT_abs = m.addVar(lb=0.0, vtype=GRB.CONTINUOUS, name="RT_abs")
    w_i = {}
    for i in range(len(P_dummy)):
        w_i[i] = m.addVar(vtype=GRB.BINARY, name=f"w_{i}")
        m.addConstr(RT_abs >= r_i_abs[i], name=f"RT_ge_{i}")
        m.addConstr(RT_abs <= r_i_abs[i] + M*(1 - w_i[i]), name=f"RT_le_{i}")
    m.addConstr(gp.quicksum(w_i[i] for i in range(len(P_dummy))) == 1, name="pickmax_RT")

    RT_res = m.addVar(lb=0.0, name="RT_res")
    m.addConstr(RT_res >= RT_abs - state.t, name="RT_res_def")

    t_phase = (state.t % T) / T
    x_vars = [m.addVar(lb=0.0, ub=1.0, name=n) for n in ["x_t","x_bmin","x_bmax","x_bbar","x_rt"]]
    m.addConstr(x_vars[0] == 1.0 - t_phase,         name="x_t_eq")
    m.addConstr(x_vars[1] == 1.0 - B_minus/T,       name="x_bmin_eq")
    m.addConstr(x_vars[2] == 1.0 - B_plus/T,        name="x_bmax_eq")
    m.addConstr(x_vars[3] == 1.0 - B_bar/T,         name="x_bbar_eq")
    m.addConstr(x_vars[4] == 1.0 - RT_res/T,        name="x_rt_eq")

    W1, b1, W2, b2 = extract_relu_weights(relu_model)
    vhat = add_relu_block_34_38(m, x_vars, W1, b1, W2, b2, xL=[0]*5, xU=[1]*5, name="vfa")

    for v in Vset:
        for k in Kset:
            x[v,k].Start = 1.0 if feas[(v,k)] == 1 else 0.0
        break

    served = gp.quicksum(x[v,k] for v in Vset for k in Kset)
    m.setObjective(served + float(lambda_vfa * vfa_scale) * vhat, GRB.MAXIMIZE)
    m.optimize()

    action: Action = {}; served_idx = []
    for v in Vset:
        for k in Kset:
            if x[v,k].X > 0.5:
                served_idx.append(k)
                req = pending[k]
                action[v] = [(state.vehicles[v].node, req.pickup), (req.pickup, req.drop)]
                break
    return action, float(m.ObjVal), served_idx

# ---------- rollout targets (only for heuristic-target trainer) ----------
def estimate_return_rollout(coords, tt, base_state: State, P_dummy, H=ROLLOUT_H, dt=2.0, service_time=1.0,
                            slack_low=0.5, slack_high=2.0):
    st = State(base_state.T, base_state.t, tt, coords, [Vehicle(v.id, v.capacity, v.time, v.node, v.load)
                                                        for v in base_state.vehicles])
    pending: List[Request] = []
    ret = 0.0; disc = 1.0
    for _ in range(H):
        req = generate_request(st, slack_low=slack_low, slack_high=slack_high, service_time=service_time)
        pending.append(req)
        pending = [r for r in pending if r.deadline >= st.t]
        a, _ = pick_best_action_heur(st, req, P_dummy, service_time)
        r = immediate_reward(a)
        st = apply_action(st, req, a, service_time)
        if r > 0: pending.pop()
        ret += disc * r
        disc *= GAMMA
        st.t += dt
    return ret

def build_training_samples(coords, tt, P_dummy, n_samples=TRAIN_SAMPLES, service_time=1.0, seed=123):
    random.seed(seed); np.random.seed(seed)
    vehicles = make_initial_vehicles(coords)
    st = State(10.0, 0.0, tt, coords, vehicles)
    samples = []
    for _ in range(n_samples):
        req = generate_request(st, slack_low=0.5, slack_high=2.0, service_time=service_time)
        a, _ = pick_best_action_heur(st, req, P_dummy, service_time)
        z, Bmin_res, Bmax_res, Bbar_res, RT_res = aggregate_features_residual(st, a, P_dummy, service_time)
        x = np.array([1.0 - z[0], 1.0 - min(1.0, Bmin_res/st.T), 1.0 - min(1.0, Bmax_res/st.T),
                      1.0 - min(1.0, Bbar_res/st.T), 1.0 - min(1.0, RT_res/st.T)], dtype=float)
        st_next = State(st.T, st.t, st.tt, st.coords, [Vehicle(v.id, v.capacity, v.time, v.node, v.load)
                                                       for v in st.vehicles])
        st_next = apply_action(st_next, req, a, service_time)
        st_next.t = st.t + 2.0
        y = estimate_return_rollout(coords, tt, st_next, P_dummy, H=ROLLOUT_H, dt=2.0,
                                     service_time=service_time, slack_low=0.5, slack_high=2.0)
        samples.append((x, y))
        st.t += 0.7
    return samples

# ---------- calibration ----------
def calibrate_scale(relu: ReLUVFA, samples, target=CALIB_TARGET):
    outs = [abs(relu.predict(x)) for (x,_) in samples] if samples else [1.0]
    m = float(np.median(outs)) if outs else 1.0
    return 1.0 if m < 1e-9 else float(target / m)

# ---------- ReLU training MILP (heuristic-target) ----------
def _train_once(samples: List[Tuple[np.ndarray, float]], hidden: int, w_bound: float, timelimit: float):
    d = 5; h = hidden
    m = gp.Model("relu_fit", env=GLOBAL_ENV)
    m.Params.OutputFlag = 0; m.Params.TimeLimit = timelimit
    W1 = m.addVars(h, d, lb=-w_bound, ub=w_bound, name="W1")
    b1 = m.addVars(h,    lb=-w_bound, ub=w_bound, name="b1")
    W2 = m.addVars(h,    lb=-w_bound, ub=w_bound, name="W2")
    b2 = m.addVar(lb=-w_bound, ub=w_bound, name="b2")
    terms = []
    for n,(x,y) in enumerate(samples):
        x = np.asarray(x, dtype=float).tolist()
        sumx = sum(abs(v) for v in x)
        L = -w_bound*sumx - w_bound; U = w_bound*sumx + w_bound
        s   = m.addVars(h, lb=L, ub=U, name=f"s_{n}")
        yhi = m.addVars(h, lb=0.0, name=f"y_{n}")
        z   = m.addVars(h, vtype=GRB.BINARY, name=f"z_{n}")
        for j in range(h):
            m.addConstr(s[j] == gp.quicksum(W1[j,i]*x[i] for i in range(d)) + b1[j], name=f"sdef_{n}_{j}")
            m.addConstr(yhi[j] >= s[j],                          name=f"relu_ge_{n}_{j}")
            m.addConstr(yhi[j] <= s[j] - L*(1 - z[j]),           name=f"relu_on_{n}_{j}")
            m.addConstr(yhi[j] <= U * z[j],                      name=f"relu_off_{n}_{j}")
        yhat = m.addVar(lb=-GRB.INFINITY, name=f"yhat_{n}")
        m.addConstr(yhat == gp.quicksum(W2[j]*yhi[j] for j in range(h)) + b2, name=f"out_{n}")
        ep = m.addVar(lb=0.0, name=f"ep_{n}"); en = m.addVar(lb=0.0, name=f"en_{n}")
        m.addConstr(yhat - float(y) == ep - en, name=f"abs_{n}")
        terms.append(ep + en)
    m.setObjective(gp.quicksum(terms), GRB.MINIMIZE)
    m.optimize()
    W1_np = np.array([[W1[j,i].X for i in range(d)] for j in range(h)], dtype=float)
    b1_np = np.array([b1[j].X for j in range(h)], dtype=float)
    W2_np = np.array([W2[j].X for j in range(h)], dtype=float)
    b2_sc = float(b2.X)
    return W1_np, b1_np, W2_np, b2_sc

def train_relu_vfa_in_milp(samples: List[Tuple[np.ndarray, float]], hidden=RELU_HIDDEN, w_bound=W_BOUND, timelimit=TLIM_TRAIN):
    for n_try in TRAIN_LIMITS:
        use = samples[:min(n_try, len(samples))]
        try:
            return _train_once(use, hidden, w_bound, timelimit)
        except GurobiError as e:
            if "size-limited license" in str(e).lower(): continue
            else: raise
    for h_try in [max(2, hidden//2), 2]:
        for n_try in TRAIN_LIMITS[::-1]:
            use = samples[:min(n_try, len(samples))]
            try:
                return _train_once(use, h_try, w_bound, timelimit)
            except GurobiError as e:
                if "size-limited license" in str(e).lower(): continue
                else: raise
    raise RuntimeError("Training MILP too large for license.")

# ---------- episode ----------
def run_episode(state: State, P_dummy, relu_model: ReLUVFA, lam=LAMBDA_VFA, vfa_scale=1.0,
                steps=40, dt=2.0, service_time=1.0, max_pending=MAX_PENDING):
    accepted = 0
    pending: List[Request] = []
    for _ in range(steps):
        req = generate_request(state, slack_low=BASE_SLACK_LOW * DEMAND_MULT, slack_high=BASE_SLACK_HIGH * DEMAND_MULT, service_time=service_time)
        pending.append(req)
        # prune expired
        pending = [r for r in pending if r.deadline >= state.t]
        # cap queue size (drop oldest to keep size small)
        if len(pending) > max_pending:
            pending = pending[-max_pending:]
        a, obj, served_idx = plan_epoch_with_relu_vfa(
            state, pending, P_dummy, relu_model, lam, vfa_scale, service_time, TLIM_PLAN
        )
        accepted += len(served_idx)
        if a:
            (v_id, route) = next(iter(a.items()))
            v = next(vh for vh in state.vehicles if vh.id == v_id)
            tcur = v.time; node = v.node
            for (i, j) in route:
                tcur += state.tt[i, j] + service_time; node = j
            v.time = tcur; v.node = node
        for idx in sorted(served_idx, reverse=True):
            pending.pop(idx)
        state.t += dt
    return accepted

# ---------- baselines / runners ----------
def set_all_seeds(s):
    random.seed(s); np.random.seed(s); torch.manual_seed(s)

def run_heuristic_episode(coords, tt, P_dummy, steps=40, service_time=1.0):
    vehicles = make_initial_vehicles(coords)
    st = State(10.0, 0.0, tt, coords, vehicles)
    acc = 0
    for _ in range(steps):
        r = generate_request(st, slack_low=BASE_SLACK_LOW * DEMAND_MULT, slack_high=BASE_SLACK_HIGH * DEMAND_MULT, service_time=service_time)
        a, _ = pick_best_action_heur(st, r, P_dummy, service_time)
        acc += int(immediate_reward(a))
        st = apply_action(st, r, a, service_time)
        st.t += 2.0
    return acc

def run_milp_vfa_episode(coords, tt, P_dummy, relu_model, vfa_scale, lam, steps=40, service_time=1.0):
    vehicles = make_initial_vehicles(coords)
    st = State(10.0, 0.0, tt, coords, vehicles)
    return run_episode(st, P_dummy, relu_model, lam=lam, vfa_scale=vfa_scale, steps=steps, service_time=service_time)

def stats_report(name, vals):
    return {
        "method": name,
        "avg": mean(vals),
        "std": stdev(vals) if len(vals) > 1 else 0.0,
        "min": min(vals),
        "max": max(vals),
    }

def print_all_results(coords, tt, P_dummy,
                      relu_batch, vfa_scale_batch, lam_batch,
                      relu_joint, vfa_scale_joint, lam_joint,
                      steps=150, n_runs=20, seed0=2025):
    # ---- Single-run (use same seed for all three so they see the same request stream)
    set_all_seeds(seed0)
    acc_h_1 = run_heuristic_episode(coords, tt, P_dummy, steps=steps)
    set_all_seeds(seed0)
    acc_nm_1 = run_milp_vfa_episode(coords, tt, P_dummy, relu_batch, vfa_scale_batch, 0.0, steps=steps)
    set_all_seeds(seed0)
    acc_b_1 = run_milp_vfa_episode(coords, tt, P_dummy, relu_batch, vfa_scale_batch, lam_batch, steps=steps)
    set_all_seeds(seed0)
    acc_j_1 = run_milp_vfa_episode(coords, tt, P_dummy, relu_joint, vfa_scale_joint, lam_joint, steps=steps)

    print("\n--- Single-run (same scenario) ---")
    print(f"Heuristic accepted: {acc_h_1}")
    print(f"MILP (no VFA) accepted: {acc_nm_1}")
    print(f"Batch MILP + ReLU-VFA accepted: {acc_b_1}")
    print(f"Joint-K VFA accepted: {acc_j_1}")

    # ---- Multi-run averages (use CRN: same per-episode seed for fairness)
    seeds = [seed0 + i + 1 for i in range(n_runs)]
    res_h, res_nm, res_b, res_j = [], [], [], []
    for s in seeds:
        set_all_seeds(s); res_h.append(run_heuristic_episode(coords, tt, P_dummy, steps=steps))
        set_all_seeds(s); res_nm.append(run_milp_vfa_episode(coords, tt, P_dummy, relu_batch, vfa_scale_batch, 0.0, steps=steps))
        set_all_seeds(s); res_b.append(run_milp_vfa_episode(coords, tt, P_dummy, relu_batch, vfa_scale_batch, lam_batch, steps=steps))
        set_all_seeds(s); res_j.append(run_milp_vfa_episode(coords, tt, P_dummy, relu_joint, vfa_scale_joint, lam_joint, steps=steps))

    print("\n--- Multi-run (averages over episodes) ---")
    print(stats_report("Heuristic", res_h))
    print(stats_report("MILP (no VFA)", res_nm))
    print(stats_report("Batch MILP + ReLU-VFA", res_b))
    print(stats_report("Joint-K VFA", res_j))

# ---------- joint-K trainer (end-to-end over horizon K) ----------
def train_vfa_over_k(coords, tt, base_state: State, P_dummy, K=JOINT_K, hidden=RELU_HIDDEN, w_bound=W_BOUND,
                     timelimit=TLIM_TRAIN, dt=2.0, service_time=1.0, lam=LAMBDA_VFA, gamma=GAMMA):
    V = len(base_state.vehicles)
    T = max(base_state.T, 1e-6)
    m = gp.Model("jointK", env=GLOBAL_ENV)
    m.Params.OutputFlag = 0; m.Params.TimeLimit = timelimit
    m.Params.MIPFocus = 1; m.Params.Heuristics = 0.2

    # fixed K exogenous requests
    st_tmp = State(base_state.T, base_state.t, tt, coords,
                   [Vehicle(v.id, v.capacity, v.time, v.node, v.load) for v in base_state.vehicles])
    reqs = []
    for k in range(K):
        r = generate_request(st_tmp, slack_low=0.5, slack_high=2.0, service_time=service_time)
        reqs.append(r)
        st_tmp.t += dt

    # decision vars over horizon
    x = m.addVars(V, K, vtype=GRB.BINARY, name="x")
    B = m.addVars(V, K, lb=0.0, name="B")
    R = m.addVars(V, K, lb=0.0, name="R")

    # shared ReLU weights (learned jointly with x)
    W1 = m.addVars(hidden, 5, lb=-w_bound, ub=w_bound, name="W1")
    b1 = m.addVars(hidden,    lb=-w_bound, ub=w_bound, name="b1")
    W2 = m.addVars(hidden,    lb=-w_bound, ub=w_bound, name="W2")
    b2 = m.addVar(lb=-w_bound, ub=w_bound, name="b2")

    v_node0 = [base_state.vehicles[v].node for v in range(V)]
    v_time0 = [base_state.vehicles[v].time for v in range(V)]
    v_cap   = [base_state.vehicles[v].capacity for v in range(V)]

    M = float(base_state.T + (np.max(tt) if tt.size else 0.0) + 100.0)

    # (NEW) enforce at most one assignment per vehicle across the whole horizon
    for v in range(V):
        m.addConstr(gp.quicksum(x[v,k] for k in range(K)) <= 1, name=f"one_job_total_{v}")

    # keep references we need later (no getVarByName)
    vhat_vars = []
    RTres_vars = []

    for k in range(K):
        # each request can be served by at most one vehicle (once)
        m.addConstr(gp.quicksum(x[v,k] for v in range(V)) <= 1, name=f"assign_once_{k}")
        for v in range(V):
            m.addConstr(reqs[k].pax * x[v,k] <= v_cap[v], name=f"cap_{v}_{k}")

        for v in range(V):
            travel = tt[v_node0[v], reqs[k].pickup] + service_time + tt[reqs[k].pickup, reqs[k].drop] + service_time
            if k == 0:
                m.addConstr(B[v,k] == v_time0[v] + travel * x[v,k], name=f"B_{v}_{k}")
            else:
                m.addConstr(B[v,k] >= B[v,k-1], name=f"Bprop_ge_{v}_{k}")
                m.addConstr(B[v,k] >= B[v,k-1] + travel * x[v,k], name=f"Bprop_add_{v}_{k}")

        for v in range(V):
            m.addConstr(B[v,k] <= reqs[k].deadline + M*(1 - x[v,k]), name=f"ddl_{v}_{k}")

        t_k = base_state.t + k*dt
        for v in range(V):
            m.addConstr(R[v,k] >= B[v,k] - t_k, name=f"res_{v}_{k}")

        Bminus = add_min_over(m, [R[v,k] for v in range(V)], M, name=f"Bminus_k{k}")
        Bplus  = add_max_over(m, [R[v,k] for v in range(V)], M, name=f"Bplus_k{k}")
        Bbar   = m.addVar(lb=0.0, name=f"Bbar_k{k}")
        m.addConstr(Bbar == (1.0/V) * gp.quicksum(R[v,k] for v in range(V)), name=f"Bbar_def_k{k}")

        # worst-case response time via dummy grid (based on initial node; consistent with one-job constraint)
        r_iv_abs = {}
        for i in range(len(P_dummy)):
            for v in range(V):
                d_idle = _dist_node_to_point(coords, v_node0[v], P_dummy[i])
                d_switch = d_idle + x[v,k] * (_dist_node_to_point(coords, reqs[k].drop, P_dummy[i]) - d_idle)
                r_iv_abs[(i,v)] = m.addVar(lb=0.0, name=f"rabs_{i}_{v}_k{k}")
                m.addConstr(r_iv_abs[(i,v)] == B[v,k] + d_switch, name=f"rabs_def_{i}_{v}_k{k}")
        r_i_abs = {i: add_min_over(m, [r_iv_abs[(i,v)] for v in range(V)], M, name=f"rtmin_i{i}_k{k}")
                   for i in range(len(P_dummy))}
        RT_abs = add_max_over(m, [r_i_abs[i] for i in range(len(P_dummy))], M, name=f"RTabs_k{k}")
        RT_res = m.addVar(lb=0.0, name=f"RTres_k{k}")
        m.addConstr(RT_res >= RT_abs - t_k, name=f"RTres_def_k{k}")
        RTres_vars.append(RT_res)

        # oriented inputs
        t_phase = ((base_state.t + k*dt) % T) / T
        x_t   = m.addVar(lb=0.0, ub=1.0, name=f"x_t_k{k}")
        x_bmin= m.addVar(lb=0.0, ub=1.0, name=f"x_bmin_k{k}")
        x_bmax= m.addVar(lb=0.0, ub=1.0, name=f"x_bmax_k{k}")
        x_bbar= m.addVar(lb=0.0, ub=1.0, name=f"x_bbar_k{k}")
        x_rt  = m.addVar(lb=0.0, ub=1.0, name=f"x_rt_k{k}")
        m.addConstr(x_t   == 1.0 - t_phase,       name=f"x_t_eq_k{k}")
        m.addConstr(x_bmin== 1.0 - Bminus/T,      name=f"x_bmin_eq_k{k}")
        m.addConstr(x_bmax== 1.0 - Bplus/T,       name=f"x_bmax_eq_k{k}")
        m.addConstr(x_bbar== 1.0 - Bbar/T,        name=f"x_bbar_eq_k{k}")
        m.addConstr(x_rt  == 1.0 - RT_res/T,      name=f"x_rt_eq_k{k}")

        # shared ReLU (piecewise-linear, idealized with big-M)
        s = m.addVars(hidden, lb=-GRB.INFINITY, name=f"s_k{k}")
        y = m.addVars(hidden, lb=0.0, name=f"y_k{k}")
        z = m.addVars(hidden, vtype=GRB.BINARY, name=f"z_k{k}")
        L = -w_bound*5.0 - w_bound
        U =  w_bound*5.0 + w_bound
        for j in range(hidden):
            m.addConstr(s[j] == W1[j,0]*x_t + W1[j,1]*x_bmin + W1[j,2]*x_bmax + W1[j,3]*x_bbar + W1[j,4]*x_rt + b1[j], name=f"sdef_k{k}_j{j}")
            m.addConstr(y[j] >= s[j],                            name=f"relu_ge_k{k}_j{j}")
            m.addConstr(y[j] <= s[j] - L*(1 - z[j]),             name=f"relu_on_k{k}_j{j}")
            m.addConstr(y[j] <= U * z[j],                        name=f"relu_off_k{k}_j{j}")
        vhat_k = m.addVar(lb=-GRB.INFINITY, name=f"vhat_k{k}")
        m.addConstr(vhat_k == gp.quicksum(W2[j]*y[j] for j in range(hidden)) + b2, name=f"out_k{k}")
        vhat_vars.append(vhat_k)

    # objective: sum_k gamma^k (served_k + lam * vhat_k)   [use function args, not globals]
    obj_terms = []
    for k in range(K):
        served_k = gp.quicksum(x[v,k] for v in range(V))
        obj_terms.append((gamma**k) * (served_k + lam * vhat_vars[k]))
    m.setObjective(gp.quicksum(obj_terms), GRB.MAXIMIZE)
    m.optimize()

    # extract weights directly from variable arrays (no names)
    W1_np = np.array([[W1[j,i].X for i in range(5)] for j in range(hidden)], dtype=float)
    b1_np = np.array([b1[j].X for j in range(hidden)], dtype=float)
    W2_np = np.array([W2[j].X for j in range(hidden)], dtype=float)
    b2_sc = float(b2.X)

    # build joint-K inputs for calibration (from R and RTres)
    joint_inputs = []
    for k in range(K):
        Rvk = [R[v,k].X for v in range(V)]
        Bmin_val = min(Rvk) if Rvk else 0.0
        Bmax_val = max(Rvk) if Rvk else 0.0
        Bbar_val = sum(Rvk)/len(Rvk) if Rvk else 0.0
        RT_val = RTres_vars[k].X
        t_k = base_state.t + k*dt
        t_phase = (t_k % T) / T
        x_vec = np.array([1.0 - t_phase,
                          1.0 - min(1.0, Bmin_val/T),
                          1.0 - min(1.0, Bmax_val/T),
                          1.0 - min(1.0, Bbar_val/T),
                          1.0 - min(1.0, RT_val/T)], dtype=float)
        joint_inputs.append(x_vec)

    return W1_np, b1_np, W2_np, b2_sc, joint_inputs

# ---------- demos ----------
def tiny_demo():
    coords, tt = make_grid(5, 10.0)
    P_dummy = make_dummy_points(JOINT_GRID_SIDE, 2.0)
    relu = ReLUVFA(hidden=RELU_HIDDEN)

    samples = build_training_samples(coords, tt, P_dummy, n_samples=TRAIN_SAMPLES)
    try:
        W1, b1, W2, b2 = train_relu_vfa_in_milp(samples, hidden=RELU_HIDDEN, w_bound=W_BOUND, timelimit=TLIM_TRAIN)
    except GurobiError as e:
        msg = str(e).lower()
        if "size-limited license" in msg or "restricted license" in msg:
            W1 = np.zeros((RELU_HIDDEN,5)); b1 = np.zeros(RELU_HIDDEN); W2 = np.zeros(RELU_HIDDEN); b2 = 0.0
            print("[warn] fell back to zero weights due to license size limit")
        else:
            raise

    with torch.no_grad():
        l1, _, l2 = relu.model
        if l1.weight.shape[0] != W1.shape[0]:
            relu.model = nn.Sequential(nn.Linear(5, W1.shape[0]), nn.ReLU(), nn.Linear(W1.shape[0], 1))
            l1, _, l2 = relu.model
        l1.weight.copy_(torch.tensor(W1, dtype=torch.float32))
        l1.bias.copy_(torch.tensor(b1, dtype=torch.float32))
        l2.weight.copy_(torch.tensor(W2.reshape(1,-1), dtype=torch.float32))
        l2.bias.copy_(torch.tensor([b2], dtype=torch.float32))

    print(f"[train] hidden={W1.shape[0]}  ||W1||_inf={np.max(np.abs(W1)):.3f}  ||W2||_inf={np.max(np.abs(W2)):.3f}  |b2|={abs(b2):.3f}")
    preds = [abs(relu.predict(x)) for (x, _) in samples]
    med = float(np.median(preds)) if preds else 0.0
    vfa_scale = calibrate_scale(relu, samples, target=CALIB_TARGET)
    print(f"[calib] median|Vhat| = {med:.3f}  target={CALIB_TARGET:.3f}  scale={vfa_scale:.3f}")

    vehicles = make_initial_vehicles(coords)
    st1 = State(10.0, 0.0, tt, coords, [Vehicle(v.id, v.capacity, v.time, v.node, v.load) for v in vehicles])
    acc_h = 0
    for _ in range(150):
        r = generate_request(st1, slack_low=BASE_SLACK_LOW * DEMAND_MULT, slack_high=BASE_SLACK_HIGH * DEMAND_MULT)
        a, _ = pick_best_action_heur(st1, r, P_dummy)
        acc_h += int(immediate_reward(a))
        st1 = apply_action(st1, r, a)
        st1.t += 2.0
    print("Heuristic accepted:", acc_h)

    st2 = State(10.0, 0.0, tt, coords, [Vehicle(v.id, v.capacity, v.time, v.node, v.load) for v in vehicles])
    acc_vfa = run_episode(st2, P_dummy, relu, lam=LAMBDA_VFA, vfa_scale=vfa_scale, steps=150, service_time=1.0)
    print("Batch MILP + ReLU-VFA accepted:", acc_vfa)

    return relu, vfa_scale, coords, tt, P_dummy


def tiny_demo_joint_k(coords, tt, P_dummy):

    vehicles = make_initial_vehicles(coords)
    base_state = State(
        10.0, 0.0, tt, coords, vehicles
       )


    W1, b1, W2, b2, joint_inputs = train_vfa_over_k(
        coords, tt, base_state, P_dummy,
        K=JOINT_K, hidden=RELU_HIDDEN, w_bound=W_BOUND_JOINT,
        timelimit=TLIM_TRAIN, dt=2.0, service_time=1.0,
        lam=LAMBDA_VFA_JOINT, gamma=GAMMA
    )

    relu = ReLUVFA(hidden=W1.shape[0])

    with torch.no_grad():
        l1, _, l2 = relu.model
        if l1.weight.shape[0] != W1.shape[0]:
            relu.model = nn.Sequential(
                nn.Linear(5, W1.shape[0]),
                nn.ReLU(),
                nn.Linear(W1.shape[0], 1)
            )
            l1, _, l2 = relu.model

        l1.weight.copy_(torch.tensor(W1, dtype=torch.float32))
        l1.bias.copy_(torch.tensor(b1, dtype=torch.float32))
        l2.weight.copy_(torch.tensor(W2.reshape(1,-1), dtype=torch.float32))
        l2.bias.copy_(torch.tensor([b2], dtype=torch.float32))

    preds_joint = [abs(relu.predict(x)) for x in joint_inputs] if joint_inputs else [1.0]
    med_joint = float(np.median(preds_joint))
    raw_scale = 1.0 if med_joint < 1e-9 else float(CALIB_TARGET / med_joint)
    vfa_scale_joint = max(0.08, raw_scale)

    print(f"[calib-joint] median|Vhat| = {med_joint:.3f} "
          f" target={CALIB_TARGET:.3f} scale={vfa_scale_joint:.3f}")

    return relu, vfa_scale_joint


if __name__ == "__main__":
    # Batch (heuristic-target) trainer
    relu_b, vfa_scale_b, coords, tt, P_dummy = tiny_demo()

    # Joint-K (end-to-end) trainer using SAME coords & P_dummy
    relu_j, vfa_scale_j = tiny_demo_joint_k(coords, tt, P_dummy)

    # Evaluation across methods
    print_all_results(
        coords, tt, P_dummy,
        relu_batch=relu_b, vfa_scale_batch=vfa_scale_b, lam_batch=LAMBDA_VFA,
        relu_joint=relu_j, vfa_scale_joint=vfa_scale_j, lam_joint=LAMBDA_VFA_JOINT,
        steps=150, n_runs=50, seed0=2025
    )