# -*- coding: utf-8 -*-
"""vfa_advantage_torch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I-JlCso-EZzwiQTqIRID3iqCXSDmanoh
"""

import gurobipy as gp
from gurobipy import GRB, GurobiError

WLS_ACCESS_ID = "WLS_ACCESS_ID"
WLS_SECRET = "WLS_SECRET"
LICENSE_ID = LICENSE_ID

GLOBAL_ENV = gp.Env(empty=True)
GLOBAL_ENV.setParam("WLSAccessID", WLS_ACCESS_ID)
GLOBAL_ENV.setParam("WLSSecret", WLS_SECRET)
GLOBAL_ENV.setParam("LICENSEID", LICENSE_ID)
GLOBAL_ENV.start()

_test = gp.Model("license_check", env=GLOBAL_ENV)
_test.optimize()

import random
from dataclasses import dataclass
from typing import List, Tuple, Dict
from math import hypot
import numpy as np
import torch
import torch.nn as nn
from statistics import mean, stdev
from itertools import permutations, combinations

# --- knobs ---
RANDOM_SEED   = 42
RELU_HIDDEN   = 8
W_BOUND       = 10.0
TRAIN_SAMPLES = 600
ROLLOUT_H     = 10
GAMMA         = 0.95
LAMBDA_VFA    = 1.0     # stronger VFA weight
CALIB_TARGET  = 2.0     # larger typical |lambda * scale * Vhat|
TLIM_TRAIN    = 60.0
TLIM_PLAN     = 5.0
JOINT_GRID_SIDE = 3
MAX_PENDING   = 6
DEMAND_MULT   = 1.0     # no slack shrink
BASE_SLACK_LOW  = 0.5
BASE_SLACK_HIGH = 5.0   # more slack -> more feasible plans
N_VEHICLES    = 15

# Poisson arrival rate (per unit time)
ARRIVAL_RATE  = 0.7

# VFA feature dimension: original 5 + 2 pending-request features
FEAT_DIM = 7
SLACK_SCALE_MULT = 3.0  # used in both numeric and MILP feature scaling

random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)
torch.manual_seed(RANDOM_SEED)

GLOBAL_ENV = gp.Env(empty=True)
GLOBAL_ENV.setParam('OutputFlag', 0)
GLOBAL_ENV.start()

NodeId = int
Action = Dict[int, List[Tuple[int, int]]]

@dataclass
class Vehicle:
    id: int
    capacity: int
    time: float
    node: NodeId
    load: int = 0

@dataclass
class State:
    T: float
    t: float
    tt: np.ndarray
    coords: List[Tuple[float, float]]
    vehicles: List[Vehicle]

@dataclass
class Request:
    pickup: int
    drop: int
    pax: int
    deadline: float

def make_initial_vehicles(coords):
    if N_VEHICLES == 2:
        return [
            Vehicle(0, 2, 0.0, 0),
            Vehicle(1, 2, 0.0, len(coords) - 1),
        ]
    elif N_VEHICLES == 3:
        center = len(coords) // 2
        return [
            Vehicle(0, 2, 0.0, 0),
            Vehicle(1, 2, 0.0, center),
            Vehicle(2, 2, 0.0, len(coords) - 1),
        ]
    else:
        vehicles = []
        n_nodes = len(coords)
        for vid in range(N_VEHICLES):
            node = int(vid * (n_nodes - 1) / max(1, N_VEHICLES - 1))
            vehicles.append(Vehicle(vid, 2, 0.0, node))
        return vehicles

def make_grid(n_side: int, area: float):
    coords = []
    step = area / (n_side - 1) if n_side > 1 else 0.0
    for r in range(n_side):
        for c in range(n_side):
            coords.append((r * step, c * step))
    N = n_side * n_side
    tt = np.zeros((N, N), dtype=float)
    for i, (xi, yi) in enumerate(coords):
        for j, (xj, yj) in enumerate(coords):
            tt[i, j] = 0.0 if i == j else ((xi - xj) ** 2 + (yi - yj) ** 2) ** 0.5
    return coords, tt

def make_dummy_points(k_side: int, area: float):
    pts = []
    step = area / (k_side + 1)
    for r in range(1, k_side + 1):
        for c in range(1, k_side + 1):
            pts.append((r * step, c * step))
    return pts

def _dist_node_to_point(coords, j: NodeId, pt: Tuple[float, float]) -> float:
    xj, yj = coords[j]
    x, y = pt
    return hypot(xj - x, yj - y)

def generate_request(state: State, pax_min=1, pax_max=2,
                     slack_low=0.5, slack_high=2.0, service_time=1.0) -> Request:
    N = len(state.coords)
    p = random.randrange(N)
    d = random.randrange(N)
    while d == p:
        d = random.randrange(N)
    pax = random.randint(pax_min, pax_max)
    travel_pd = state.tt[p, d]
    deadline = state.t + travel_pd + 2 * service_time + random.uniform(slack_low, slack_high)
    return Request(pickup=p, drop=d, pax=pax, deadline=deadline)

def enumerate_actions(state: State, req: Request, service_time: float = 1.0) -> List[Action]:
    cands = [{}]  # include "do nothing"
    for v in state.vehicles:
        if v.load + req.pax > v.capacity:
            continue
        arr_pick = v.time + state.tt[v.node, req.pickup] + service_time
        arr_drop = arr_pick + state.tt[req.pickup, req.drop] + service_time
        if arr_drop <= req.deadline:
            cands.append({v.id: [(v.node, req.pickup), (req.pickup, req.drop)]})
    return cands

def immediate_reward(a: Action) -> float:
    return 0.0 if not a else 1.0

def apply_action(state: State, a: Action, service_time: float = 1.0) -> State:
    if not a:
        return state
    for v_id, route in a.items():
        v = next(vh for vh in state.vehicles if vh.id == v_id)
        t = v.time
        node = v.node
        for (i, j) in route:
            t += state.tt[i, j] + service_time
            node = j
        v.time = t
        v.node = node
    return state

def finish_times_and_last_nodes(state: State, action: Action, service_time: float = 1.0):
    B_v = []
    last_nodes = []
    for v in state.vehicles:
        t = v.time
        node = v.node
        for (i, j) in action.get(v.id, []):
            t += state.tt[i, j] + service_time
            node = j
        B_v.append(t)
        last_nodes.append(node)
    return np.array(B_v, dtype=float), last_nodes

def response_time_RT_abs(state: State, B_v: np.ndarray,
                         last_nodes: List[NodeId],
                         dummy_points: List[Tuple[float, float]]) -> float:
    worst = 0.0
    for pt in dummy_points:
        best_here = min(B_v[idx] + _dist_node_to_point(state.coords, last_nodes[idx], pt)
                        for idx in range(len(B_v)))
        worst = max(worst, best_here)
    return worst

def aggregate_features_residual(state: State, action: Action,
                                dummy_points: List[Tuple[float, float]],
                                service_time: float = 1.0):
    T = max(state.T, 1e-6)
    B_v_abs, last_nodes = finish_times_and_last_nodes(state, action, service_time)
    if len(B_v_abs) == 0:
        Bmin_res = Bmax_res = Bbar_res = RT_res = 0.0
    else:
        B_res = np.maximum(0.0, B_v_abs - state.t)
        Bmin_res = float(B_res.min())
        Bmax_res = float(B_res.max())
        Bbar_res = float(B_res.mean())
        RT_abs = response_time_RT_abs(state, B_v_abs, last_nodes, dummy_points)
        RT_res = max(0.0, RT_abs - state.t)
    t_phase = (state.t % T) / T
    z = np.array([
        t_phase,
        min(1.0, Bmin_res / T),
        min(1.0, Bmax_res / T),
        min(1.0, Bbar_res / T),
        min(1.0, RT_res / T)
    ], dtype=np.float32)
    return z, Bmin_res, Bmax_res, Bbar_res, RT_res

def pick_best_action_heur(state: State, req: Request, P,
                          service_time=1.0):
    best_a = {}
    best_s = -1e9
    best_rt = 1e9
    for a in enumerate_actions(state, req, service_time):
        s = immediate_reward(a)
        _, _, _, _, RT_res = aggregate_features_residual(state, a, P, service_time)
        if (s > best_s) or (s == best_s and RT_res < best_rt):
            best_a = a
            best_s = s
            best_rt = RT_res
    return best_a, best_s

class ReLUVFA:
    def __init__(self, hidden=RELU_HIDDEN, device="cpu"):
        self.model = nn.Sequential(
            nn.Linear(FEAT_DIM, hidden),
            nn.ReLU(),
            nn.Linear(hidden, 1)
        ).to(device)

    def predict(self, x: np.ndarray) -> float:
        with torch.no_grad():
            t = torch.tensor(x, dtype=torch.float32).unsqueeze(0)
            return float(self.model(t).squeeze())

def extract_relu_weights(m: "ReLUVFA"):
    l1, _, l2 = m.model
    W1 = l1.weight.detach().cpu().numpy()
    b1 = l1.bias.detach().cpu().numpy()
    W2 = l2.weight.detach().cpu().numpy()
    b2 = l2.bias.detach().cpu().numpy()
    return W1, b1, W2.reshape(-1), float(b2.item())

def add_min_over(m, vals, M, name):
    n = len(vals)
    r = m.addVar(lb=-GRB.INFINITY, name=f"{name}_min")
    z = m.addVars(n, vtype=GRB.BINARY, name=f"{name}_zmin")
    for i in range(n):
        m.addConstr(r <= vals[i], name=f"{name}_min_le_{i}")
        m.addConstr(r >= vals[i] - M * (1 - z[i]), name=f"{name}_min_ge_{i}")
    m.addConstr(gp.quicksum(z[i] for i in range(n)) == 1, name=f"{name}_pick1")
    return r

def add_max_over(m, vals, M, name):
    n = len(vals)
    r = m.addVar(lb=-GRB.INFINITY, name=f"{name}_max")
    z = m.addVars(n, vtype=GRB.BINARY, name=f"{name}_zmax")
    for i in range(n):
        m.addConstr(r >= vals[i], name=f"{name}_max_ge_{i}")
        m.addConstr(r <= vals[i] + M * (1 - z[i]), name=f"{name}_max_le_{i}")
    m.addConstr(gp.quicksum(z[i] for i in range(n)) == 1, name=f"{name}_pick1")
    return r

def bounds_affine_row(w_row: np.ndarray, b: float, xL: np.ndarray, xU: np.ndarray):
    lo = b
    hi = b
    for wj, lj, uj in zip(w_row, xL, xU):
        if wj >= 0:
            lo += wj * lj
            hi += wj * uj
        else:
            lo += wj * uj
            hi += wj * lj
    return lo, hi

def add_relu_block_34_38(m, x_vars, W1, b1, W2, b2, xL, xU, name="vfa"):
    d = len(x_vars)
    h = W1.shape[0]
    s = m.addVars(h, lb=-GRB.INFINITY, name=f"{name}_s")
    y = m.addVars(h, lb=0.0, name=f"{name}_y")
    z = m.addVars(h, vtype=GRB.BINARY, name=f"{name}_z")
    for j in range(h):
        L, U = bounds_affine_row(W1[j], b1[j], np.array(xL), np.array(xU))
        if U < L:
            L, U = U, L
        if abs(U - L) < 1e-6:
            U += 1e-6
        m.addConstr(
            s[j] == gp.quicksum(float(W1[j, i]) * x_vars[i] for i in range(d)) + float(b1[j]),
            name=f"{name}_aff_{j}"
        )
        m.addConstr(y[j] >= s[j], name=f"{name}_y_ge_s_{j}")
        m.addConstr(y[j] <= s[j] - L * (1 - z[j]), name=f"{name}_relu_on_{j}")
        m.addConstr(y[j] <= U * z[j], name=f"{name}_relu_off_{j}")
    vhat = m.addVar(lb=-GRB.INFINITY, name=f"{name}_out")
    m.addConstr(
        vhat == gp.quicksum(float(W2[j]) * y[j] for j in range(h)) + float(b2),
        name=f"{name}_out_def"
    )
    return vhat

def enumerate_vehicle_plans(state: State, pending: List[Request], v_idx: int,
                            service_time: float = 1.0):
    v = state.vehicles[v_idx]
    tt = state.tt
    plans = []

    # empty plan
    plans.append({
        "served_idx": [],
        "route": [],
        "B": v.time,
        "last_node": v.node,
    })

    Nreq = len(pending)
    if Nreq == 0:
        return plans

    def simulate_sequence(events):
        t = v.time
        node = v.node
        load = 0
        cap = v.capacity
        for etype, k in events:
            req = pending[k]
            if etype == "pickup":
                t += tt[node, req.pickup] + service_time
                load += req.pax
                if load > cap:
                    return False, None, None
                node = req.pickup
            else:
                t += tt[node, req.drop] + service_time
                load -= req.pax
                if t > req.deadline:
                    return False, None, None
                node = req.drop
        return True, t, node

    # single-request plans
    for k in range(Nreq):
        req = pending[k]
        arr_pick = v.time + tt[v.node, req.pickup] + service_time
        arr_drop = arr_pick + tt[req.pickup, req.drop] + service_time
        if arr_drop <= req.deadline and req.pax <= v.capacity:
            ok, B, last_node = simulate_sequence([
                ("pickup", k),
                ("drop", k),
            ])
            if ok:
                plans.append({
                    "served_idx": [k],
                    "route": [
                        (v.node, req.pickup),
                        (req.pickup, req.drop),
                    ],
                    "B": B,
                    "last_node": last_node,
                })

    # two-request shared plans
    for k1, k2 in combinations(range(Nreq), 2):
        r1, r2 = pending[k1], pending[k2]
        if r1.pax + r2.pax > v.capacity:
            continue
        events = [
            ("pickup", k1),
            ("drop",   k1),
            ("pickup", k2),
            ("drop",   k2),
        ]
        for perm in set(permutations(events, 4)):
            seen_pick1 = False
            seen_pick2 = False
            valid = True
            for etype, k in perm:
                if k == k1:
                    if etype == "pickup":
                        seen_pick1 = True
                    else:
                        if not seen_pick1:
                            valid = False
                            break
                else:
                    if etype == "pickup":
                        seen_pick2 = True
                    else:
                        if not seen_pick2:
                            valid = False
                            break
            if not valid:
                continue
            ok, B, last_node = simulate_sequence(perm)
            if not ok:
                continue
            route = []
            cur_node = v.node
            for etype, k in perm:
                req = pending[k]
                target = req.pickup if etype == "pickup" else req.drop
                route.append((cur_node, target))
                cur_node = target
            plans.append({
                "served_idx": sorted([k1, k2]),
                "route": route,
                "B": B,
                "last_node": last_node,
            })

    return plans

# --- feature builder ---
def build_feature_vector(state: State,
                         action: Action,
                         pending: List[Request],
                         served_idx: List[int],
                         dummy_points: List[Tuple[float, float]],
                         service_time: float = 1.0) -> np.ndarray:
    # aggregate core time-based residual features
    z, Bmin_res, Bmax_res, Bbar_res, RT_res = aggregate_features_residual(
        state, action, dummy_points, service_time
    )
    T = max(state.T, 1e-6)

    N_init = len(pending)
    served_set = set(served_idx)
    remaining_indices = [k for k in range(N_init) if k not in served_set]
    N_rem = len(remaining_indices)

    slack_vals = [
        max(0.0, pending[k].deadline - state.t) for k in remaining_indices
    ]
    total_slack_rem = sum(slack_vals)

    x = np.zeros(FEAT_DIM, dtype=float)

    # 0) phase in horizon [0,1]
    x[0] = z[0]  # (state.t % T) / T

    # 1–4) unclipped residuals normalized by T
    x[1] = Bmin_res / T if T > 0 else 0.0
    x[2] = Bmax_res / T if T > 0 else 0.0
    x[3] = Bbar_res / T if T > 0 else 0.0
    x[4] = RT_res   / T if T > 0 else 0.0

    # 5) remaining-request fraction
    x[5] = N_rem / float(MAX_PENDING) if MAX_PENDING > 0 else 0.0

    # 6) remaining slack scaled
    scale_slack = max(1.0, T * MAX_PENDING * SLACK_SCALE_MULT)
    x[6] = total_slack_rem / scale_slack

    return x

def plan_epoch_with_relu_vfa(state: State, pending: List[Request], P_dummy: List[Tuple[float, float]],
                             relu_model: ReLUVFA, lambda_vfa=LAMBDA_VFA, vfa_scale=1.0,
                             service_time=1.0, timelimit=TLIM_PLAN):
    Vset = list(range(len(state.vehicles)))
    Kset = list(range(len(pending)))
    T = max(state.T, 1e-6)
    tt = state.tt

    vehicle_plans = []
    for v in Vset:
        plans_v = enumerate_vehicle_plans(state, pending, v, service_time=service_time)
        if not plans_v:
            plans_v = [{
                "served_idx": [],
                "route": [],
                "B": state.vehicles[v].time,
                "last_node": state.vehicles[v].node,
            }]
        vehicle_plans.append(plans_v)

    max_tt = float(np.max(tt) if tt.size else 0.0)
    M = float(T + max_tt + 100.0)

    m = gp.Model("epoch_vfa_rideshare", env=GLOBAL_ENV)
    m.Params.OutputFlag = 0
    m.Params.TimeLimit = timelimit
    m.Params.MIPFocus = 1
    m.Params.Heuristics = 0.2

    # plan-choice binaries
    y = {}
    for v in Vset:
        for p in range(len(vehicle_plans[v])):
            y[(v, p)] = m.addVar(vtype=GRB.BINARY, name=f"y_{v}_{p}")

    for v in Vset:
        m.addConstr(
            gp.quicksum(y[(v, p)] for p in range(len(vehicle_plans[v]))) == 1,
            name=f"veh_one_plan_{v}"
        )

    # served indicators for each request
    s_k = {}
    for k in Kset:
        s_k[k] = m.addVar(lb=0.0, ub=1.0, name=f"s_{k}")
        expr_serv = gp.quicksum(
            y[(v, p)]
            for v in Vset
            for p, plan in enumerate(vehicle_plans[v])
            if k in plan["served_idx"]
        )
        m.addConstr(s_k[k] == expr_serv, name=f"s_eq_{k}")

    # each request served at most once
    for k in Kset:
        terms = []
        for v in Vset:
            for p, plan in enumerate(vehicle_plans[v]):
                if k in plan["served_idx"]:
                    terms.append(y[(v, p)])
        if terms:
            m.addConstr(gp.quicksum(terms) <= 1, name=f"req_once_{k}")

    # completion times and residuals
    B_v = m.addVars(Vset, lb=0.0, name="B_v")
    for v in Vset:
        m.addConstr(
            B_v[v] == gp.quicksum(vehicle_plans[v][p]["B"] * y[(v, p)]
                                  for p in range(len(vehicle_plans[v]))),
            name=f"Bv_def_{v}"
        )

    R_v = m.addVars(Vset, lb=0.0, name="R_v")
    for v in Vset:
        m.addConstr(R_v[v] >= B_v[v] - state.t, name=f"res_{v}")

    B_minus = add_min_over(m, [R_v[v] for v in Vset], M, name="Bminus")
    B_plus = add_max_over(m, [R_v[v] for v in Vset], M, name="Bplus")

    B_bar = m.addVar(lb=0.0, name="Bbar")
    if len(Vset) > 0:
        m.addConstr(
            B_bar == (1.0 / len(Vset)) * gp.quicksum(R_v[v] for v in Vset),
            name="Bbar_def"
        )

    # response times to dummy points
    r_iv_abs = {}
    for i, pt in enumerate(P_dummy):
        for v in Vset:
            r_iv_abs[(i, v)] = m.addVar(lb=0.0, name=f"rabs_{i}_{v}")
            expr = gp.quicksum(
                (vehicle_plans[v][p]["B"] +
                 _dist_node_to_point(state.coords, vehicle_plans[v][p]["last_node"], pt)) *
                y[(v, p)]
                for p in range(len(vehicle_plans[v]))
            )
            m.addConstr(r_iv_abs[(i, v)] == expr, name=f"rabs_def_{i}_{v}")

    r_i_abs = {}
    for i in range(len(P_dummy)):
        r_i_abs[i] = add_min_over(
            m, [r_iv_abs[(i, v)] for v in Vset], M, name=f"rtmin_i{i}"
        )

    RT_abs = add_max_over(
        m, [r_i_abs[i] for i in range(len(P_dummy))], M, name="RT_abs"
    )

    RT_res = m.addVar(lb=0.0, name="RT_res")
    m.addConstr(RT_res >= RT_abs - state.t, name="RT_res_def")

    # --- pending-request features (N_rem and slack) + feature vector for VFA ---

    N_init = len(Kset)
    N_serv_expr = gp.quicksum(s_k[k] for k in Kset)
    N_rem_expr = float(N_init) - N_serv_expr
    count_scale = float(MAX_PENDING) if MAX_PENDING > 0 else 1.0

    slack_const = {k: max(0.0, pending[k].deadline - state.t) for k in Kset}
    base_slack_sum = sum(slack_const.values())
    slack_served_expr = gp.quicksum(slack_const[k] * s_k[k] for k in Kset)
    total_slack_rem_expr = base_slack_sum - slack_served_expr
    slack_scale = max(1.0, state.T * MAX_PENDING * SLACK_SCALE_MULT)

    T = max(state.T, 1e-6)
    t_phase = (state.t % T) / T if T > 0 else 0.0

    # x[0] in [0,1]; x[1..4] >=0 (may exceed 1); x[5], x[6] in [0,1]
    x_t        = m.addVar(lb=0.0, ub=1.0, name="x_t")
    x_bmin     = m.addVar(lb=0.0, name="x_bmin")
    x_bmax     = m.addVar(lb=0.0, name="x_bmax")
    x_bbar     = m.addVar(lb=0.0, name="x_bbar")
    x_rt       = m.addVar(lb=0.0, name="x_rt")
    x_nrem     = m.addVar(lb=0.0, ub=1.0, name="x_nrem")
    x_slackrem = m.addVar(lb=0.0, ub=1.0, name="x_slackrem")

    # link features exactly as in build_feature_vector
    m.addConstr(x_t == t_phase, name="x_t_eq")
    m.addConstr(x_bmin == B_minus / T, name="x_bmin_eq")
    m.addConstr(x_bmax == B_plus  / T, name="x_bmax_eq")
    m.addConstr(x_bbar == B_bar   / T, name="x_bbar_eq")
    m.addConstr(x_rt   == RT_res  / T, name="x_rt_eq")

    m.addConstr(x_nrem     == N_rem_expr / count_scale,   name="x_nrem_eq")
    m.addConstr(x_slackrem == total_slack_rem_expr / slack_scale,
                name="x_slackrem_eq")

    x_vars = [x_t, x_bmin, x_bmax, x_bbar, x_rt, x_nrem, x_slackrem]

    # --- ReLU VFA with proper feature bounds ---
    W1, b1, W2, b2 = extract_relu_weights(relu_model)

    RATIO_MAX = 5.0  # upper bound on B*/T and RT_res/T for big-M
    xL = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    xU = [1.0, RATIO_MAX, RATIO_MAX, RATIO_MAX, RATIO_MAX, 1.0, 1.0]

    vhat = add_relu_block_34_38(
        m, x_vars, W1, b1, W2, b2,
        xL=xL, xU=xU,
        name="vfa"
    )

    # served requests in this epoch
    served = gp.quicksum(
        len(vehicle_plans[v][p]["served_idx"]) * y[(v, p)]
        for v in Vset for p in range(len(vehicle_plans[v]))
    )

    m.setObjective(served + float(lambda_vfa * vfa_scale) * vhat, GRB.MAXIMIZE)
    m.optimize()

    # --- NEW: guard for no feasible solution ---
    if m.SolCount == 0:
        # No solution found (e.g., time limit, infeasible) -> do nothing
        return {}, 0.0, []

    action: Action = {}
    served_idx = []

    for v in Vset:
        chosen_p = None
        for p in range(len(vehicle_plans[v])):
            if y[(v, p)].X > 0.5:
                chosen_p = p
                break
        if chosen_p is None:
            continue
        plan = vehicle_plans[v][chosen_p]
        if plan["served_idx"]:
            action[v] = list(plan["route"])
            served_idx.extend(plan["served_idx"])

    served_idx = sorted(set(served_idx))
    return action, float(m.ObjVal), served_idx

def estimate_return_rollout(coords, tt, base_state: State, P_dummy,
                            H=ROLLOUT_H, dt=2.0, service_time=1.0,
                            slack_low=0.5, slack_high=2.0):
    st = State(base_state.T, base_state.t, tt, coords,
               [Vehicle(v.id, v.capacity, v.time, v.node, v.load)
                for v in base_state.vehicles])
    pending: List[Request] = []
    ret = 0.0
    disc = 1.0
    for _ in range(H):
        n_new = np.random.poisson(ARRIVAL_RATE * dt)
        for _ in range(n_new):
            req = generate_request(st, slack_low=slack_low,
                                   slack_high=slack_high,
                                   service_time=service_time)
            pending.append(req)
        pending = [r for r in pending if r.deadline >= st.t]
        if not pending:
            st.t += dt
            disc *= GAMMA
            continue
        req = pending[-1]
        a, _ = pick_best_action_heur(st, req, P_dummy, service_time)
        r = immediate_reward(a)
        st = apply_action(st, a, service_time)
        if r > 0:
            pending.pop()
        ret += disc * r
        disc *= GAMMA
        st.t += dt
    return ret

# --- NEW: advantage-based offline training per state ---
def build_training_samples(coords, tt, P_dummy,
                           n_samples=TRAIN_SAMPLES, service_time=1.0,
                           seed=123):
    """
    Offline training data:
    - For each simulated state, consider multiple actions (including 'do nothing').
    - For each action, estimate long-run return via rollout.
    - Form ADVANTAGE targets: y(a) - y(base), where base is typically 'do nothing'.
    """
    random.seed(seed)
    np.random.seed(seed)

    vehicles = make_initial_vehicles(coords)
    st = State(10.0, 0.0, tt, coords, vehicles)
    samples: List[Tuple[np.ndarray, float]] = []
    pending: List[Request] = []
    dt = 2.0

    while len(samples) < n_samples:
        # arrivals
        n_new = np.random.poisson(ARRIVAL_RATE * dt)
        for _ in range(n_new):
            req = generate_request(
                st,
                slack_low=0.5,
                slack_high=2.0,
                service_time=service_time
            )
            pending.append(req)

        # remove expired
        pending = [r for r in pending if r.deadline >= st.t]

        # cap queue
        if len(pending) > MAX_PENDING:
            pending = pending[-MAX_PENDING:]

        # if no pending requests, just advance time
        if not pending:
            st.t += dt
            continue

        # focus on most recent request
        req_idx = len(pending) - 1
        req = pending[req_idx]

        # enumerate candidate actions (includes do-nothing)
        candidate_actions = enumerate_actions(st, req, service_time=service_time)

        # if for some reason we got no actions, fallback to do-nothing only
        if not candidate_actions:
            candidate_actions = [{}]

        # For this state, compute returns for all actions
        per_state = []  # list of (a, x, y, served_idx)
        for a in candidate_actions:
            if len(samples) >= n_samples:
                break

            if immediate_reward(a) > 0:
                served_idx = [req_idx]
            else:
                served_idx = []

            x = build_feature_vector(
                st, a, pending, served_idx, P_dummy,
                service_time=service_time
            )

            # next state after applying a once
            st_next = State(
                st.T, st.t, st.tt, st.coords,
                [Vehicle(v.id, v.capacity, v.time, v.node, v.load)
                 for v in st.vehicles]
            )
            st_next = apply_action(st_next, a, service_time)
            st_next.t = st.t + dt

            # Monte Carlo estimate of long-run value of this action
            y = estimate_return_rollout(
                coords, tt, st_next, P_dummy,
                H=ROLLOUT_H, dt=dt,
                service_time=service_time,
                slack_low=0.5, slack_high=2.0
            )

            per_state.append((a, x, y, served_idx))

        if per_state:
            # choose baseline: 'do nothing' if present, else min-y action
            base_candidates = [y for (a, x, y, served_idx) in per_state if not a]
            if base_candidates:
                y_base = base_candidates[0]
            else:
                y_base = min(y for (_, _, y, _) in per_state)

            # add advantage samples for this state
            for (a, x, y, served_idx) in per_state:
                adv = y - y_base
                samples.append((x, adv))
                if len(samples) >= n_samples:
                    break

        # advance environment state using heuristic to move forward
        a_env, _ = pick_best_action_heur(st, req, P_dummy, service_time)
        if immediate_reward(a_env) > 0 and pending:
            pending.pop(req_idx)
        st = apply_action(st, a_env, service_time)
        st.t += dt

    return samples

def build_training_samples_onpolicy(coords, tt, P_dummy,
                                    relu_model, vfa_scale,
                                    n_samples=TRAIN_SAMPLES,
                                    service_time=1.0,
                                    seed=123):
    random.seed(seed)
    np.random.seed(seed)
    vehicles = make_initial_vehicles(coords)
    st = State(10.0, 0.0, tt, coords, vehicles)
    samples = []
    pending: List[Request] = []
    dt = 2.0

    while len(samples) < n_samples:
        n_new = np.random.poisson(ARRIVAL_RATE * dt)
        for _ in range(n_new):
            req = generate_request(
                st,
                slack_low=BASE_SLACK_LOW * DEMAND_MULT,
                slack_high=BASE_SLACK_HIGH * DEMAND_MULT,
                service_time=service_time
            )
            pending.append(req)
        pending = [r for r in pending if r.deadline >= st.t]

        # cap queue like run_episode
        if len(pending) > MAX_PENDING:
            pending = pending[-MAX_PENDING:]

        if not pending:
            st.t += dt
            continue

        a, obj, served_idx = plan_epoch_with_relu_vfa(
            st, pending, P_dummy, relu_model,
            lambda_vfa=LAMBDA_VFA, vfa_scale=vfa_scale,
            service_time=service_time, timelimit=TLIM_PLAN
        )

        x = build_feature_vector(st, a, pending, served_idx, P_dummy,
                                 service_time=service_time)

        # Good action next-state (MILP+VFA)
        st_good = State(st.T, st.t, st.tt, st.coords,
                        [Vehicle(v.id, v.capacity, v.time, v.node, v.load)
                         for v in st.vehicles])
        st_good = apply_action(st_good, a, service_time)
        st_good.t = st.t + dt

        # Baseline: do nothing
        st_base = State(st.T, st.t, st.tt, st.coords,
                        [Vehicle(v.id, v.capacity, v.time, v.node, v.load)
                         for v in st.vehicles])
        st_base.t = st.t + dt

        y_good = estimate_return_rollout(
            coords, tt, st_good, P_dummy,
            H=ROLLOUT_H, dt=dt,
            service_time=service_time,
            slack_low=BASE_SLACK_LOW,
            slack_high=BASE_SLACK_HIGH
        )
        y_base = estimate_return_rollout(
            coords, tt, st_base, P_dummy,
            H=ROLLOUT_H, dt=dt,
            service_time=service_time,
            slack_low=BASE_SLACK_LOW,
            slack_high=BASE_SLACK_HIGH
        )
        y = y_good - y_base

        samples.append((x, y))

        for idx in sorted(served_idx, reverse=True):
            pending.pop(idx)
        st = apply_action(st, a, service_time)
        st.t += dt

    return samples

# --- VFA training with PyTorch (MSE) ---
def train_relu_vfa_torch(samples: List[Tuple[np.ndarray, float]],
                         hidden=RELU_HIDDEN,
                         lr=1e-3,
                         n_epochs=50,
                         batch_size=32) -> ReLUVFA:
    relu = ReLUVFA(hidden=hidden)
    optimizer = torch.optim.Adam(relu.model.parameters(), lr=lr)

    if not samples:
        return relu

    X = np.array([x for (x, _) in samples], dtype=np.float32)
    y = np.array([v for (_, v) in samples], dtype=np.float32).reshape(-1, 1)

    N = X.shape[0]
    for epoch in range(n_epochs):
        idx = np.random.permutation(N)
        X_shuf = X[idx]
        y_shuf = y[idx]

        for start in range(0, N, batch_size):
            end = min(start + batch_size, N)
            xb = torch.tensor(X_shuf[start:end], dtype=torch.float32)
            yb = torch.tensor(y_shuf[start:end], dtype=torch.float32)

            pred = relu.model(xb)
            loss = ((pred - yb) ** 2).mean()

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

    return relu

def calibrate_scale(relu: ReLUVFA, samples, target=CALIB_TARGET):
    outs = [abs(relu.predict(x)) for (x, _) in samples] if samples else [1.0]
    m = float(np.median(outs)) if outs else 1.0
    return 1.0 if m < 1e-9 else float(target / m)

def run_episode(state: State, P_dummy, relu_model: ReLUVFA,
                lam=LAMBDA_VFA, vfa_scale=1.0,
                steps=40, dt=2.0, service_time=1.0,
                max_pending=MAX_PENDING):
    accepted = 0
    pending: List[Request] = []
    for _ in range(steps):
        n_new = np.random.poisson(ARRIVAL_RATE * dt)
        for _ in range(n_new):
            req = generate_request(
                state,
                slack_low=BASE_SLACK_LOW * DEMAND_MULT,
                slack_high=BASE_SLACK_HIGH * DEMAND_MULT,
                service_time=service_time
            )
            pending.append(req)
        pending = [r for r in pending if r.deadline >= state.t]
        if len(pending) > max_pending:
            pending = pending[-max_pending:]
        if not pending:
            state.t += dt
            continue
        a, obj, served_idx = plan_epoch_with_relu_vfa(
            state, pending, P_dummy, relu_model, lam, vfa_scale,
            service_time, TLIM_PLAN
        )
        accepted += len(served_idx)
        state = apply_action(state, a, service_time)
        for idx in sorted(served_idx, reverse=True):
            pending.pop(idx)
        state.t += dt
    return accepted

def set_all_seeds(s):
    random.seed(s)
    np.random.seed(s)
    torch.manual_seed(s)

def run_heuristic_episode(coords, tt, P_dummy, steps=40,
                          service_time=1.0):
    vehicles = make_initial_vehicles(coords)
    st = State(10.0, 0.0, tt, coords, vehicles)
    acc = 0
    pending: List[Request] = []
    dt = 2.0
    for _ in range(steps):
        n_new = np.random.poisson(ARRIVAL_RATE * dt)
        for _ in range(n_new):
            r = generate_request(
                st,
                slack_low=BASE_SLACK_LOW * DEMAND_MULT,
                slack_high=BASE_SLACK_HIGH * DEMAND_MULT,
                service_time=service_time
            )
            pending.append(r)
        pending = [r for r in pending if r.deadline >= st.t]
        if len(pending) > MAX_PENDING:
            pending = pending[-MAX_PENDING:]
        if not pending:
            st.t += dt
            continue
        req = pending[-1]
        a, _ = pick_best_action_heur(st, req, P_dummy, service_time)
        acc += int(immediate_reward(a))
        st = apply_action(st, a, service_time)
        if immediate_reward(a) > 0:
            pending.pop()
        st.t += dt
    return acc

def run_milp_vfa_episode(coords, tt, P_dummy, relu_model, vfa_scale,
                         lam, steps=40, service_time=1.0):
    vehicles = make_initial_vehicles(coords)
    st = State(10.0, 0.0, tt, coords, vehicles)
    return run_episode(st, P_dummy, relu_model,
                       lam=lam, vfa_scale=vfa_scale,
                       steps=steps, service_time=service_time)

def stats_report(name, vals):
    return {
        "method": name,
        "avg": mean(vals),
        "std": stdev(vals) if len(vals) > 1 else 0.0,
        "min": min(vals),
        "max": max(vals),
    }

def print_all_results(coords, tt, P_dummy,
                      relu_batch, vfa_scale_batch, lam_batch,
                      relu_joint, vfa_scale_joint, lam_joint,
                      steps=150, n_runs=20, seed0=2025):
    set_all_seeds(seed0)
    acc_h_1 = run_heuristic_episode(coords, tt, P_dummy, steps=steps)
    set_all_seeds(seed0)
    acc_nm_1 = run_milp_vfa_episode(coords, tt, P_dummy, relu_batch, vfa_scale_batch, 0.0, steps=steps)
    set_all_seeds(seed0)
    acc_b_1 = run_milp_vfa_episode(coords, tt, P_dummy, relu_batch, vfa_scale_batch, lam_batch, steps=steps)
    set_all_seeds(seed0)
    acc_j_1 = run_milp_vfa_episode(coords, tt, P_dummy, relu_joint, vfa_scale_joint, lam_joint, steps=steps)

    print("\n--- Single-run (same scenario) ---")
    print(f"Heuristic accepted: {acc_h_1}")
    print(f"MILP (no VFA) accepted: {acc_nm_1}")
    print(f"Batch MILP + ReLU-VFA accepted: {acc_b_1}")
    print(f"Joint-K / on-policy VFA accepted: {acc_j_1}")

    seeds = [seed0 + i + 1 for i in range(n_runs)]
    res_h, res_nm, res_b, res_j = [], [], [], []
    for s in seeds:
        set_all_seeds(s)
        res_h.append(run_heuristic_episode(coords, tt, P_dummy, steps=steps))
        set_all_seeds(s)
        res_nm.append(run_milp_vfa_episode(coords, tt, P_dummy, relu_batch, vfa_scale_batch, 0.0, steps=steps))
        set_all_seeds(s)
        res_b.append(run_milp_vfa_episode(coords, tt, P_dummy, relu_batch, vfa_scale_batch, lam_batch, steps=steps))
        set_all_seeds(s)
        res_j.append(run_milp_vfa_episode(coords, tt, P_dummy, relu_joint, vfa_scale_joint, lam_joint, steps=steps))

    print("\n--- Multi-run (averages over episodes) ---")
    print(stats_report("Heuristic", res_h))
    print(stats_report("MILP (no VFA)", res_nm))
    print(stats_report("Batch MILP + ReLU-VFA", res_b))
    print(stats_report("On-policy VFA", res_j))

def diagnose_vfa_one_epoch(relu_model,
                           grid_side=3,
                           area=5.0,
                           n_vehicles=3,
                           n_requests=3,
                           max_assignments=2000,
                           seed=999):
    print("\n===== VFA DIAGNOSTIC (one epoch) =====")

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    coords, tt = make_grid(grid_side, area)
    P_dummy = make_dummy_points(JOINT_GRID_SIDE, 2.0)

    N = len(coords)
    center = N // 2
    vehicles = [
        Vehicle(0, 2, 0.0, 0),
        Vehicle(1, 2, 0.0, center),
        Vehicle(2, 2, 0.0, N - 1),
    ]
    vehicles = vehicles[:n_vehicles]

    state = State(T=10.0, t=0.0, tt=tt, coords=coords, vehicles=vehicles)

    pending: List[Request] = []
    for _ in range(n_requests):
        r = generate_request(
            state,
            slack_low=BASE_SLACK_LOW * DEMAND_MULT,
            slack_high=BASE_SLACK_HIGH * DEMAND_MULT,
            service_time=1.0,
        )
        pending.append(r)

    print(f"Grid side: {grid_side}, #vehicles: {len(state.vehicles)}, "
          f"#pending requests: {len(pending)}")

    Vset = list(range(len(state.vehicles)))
    vehicle_plans = []
    for v in Vset:
        plans_v = enumerate_vehicle_plans(state, pending, v, service_time=1.0)
        if not plans_v:
            plans_v = [{
                "served_idx": [],
                "route": [],
                "B": state.vehicles[v].time,
                "last_node": state.vehicles[v].node,
            }]
        vehicle_plans.append(plans_v)

    assignments = []

    def recurse(v_idx, current_choice, used_requests):
        if len(assignments) >= max_assignments:
            return
        if v_idx == len(vehicle_plans):
            assignments.append(list(current_choice))
            return
        for p_idx, plan in enumerate(vehicle_plans[v_idx]):
            s_idx = plan["served_idx"]
            if any(k in used_requests for k in s_idx):
                continue
            current_choice.append(p_idx)
            new_used = used_requests.union(s_idx)
            recurse(v_idx + 1, current_choice, new_used)
            current_choice.pop()

    recurse(0, [], set())

    print(f"Enumerated {len(assignments)} feasible global assignments "
          f"(capped at {max_assignments}).")

    rows = []
    for assign_id, choice in enumerate(assignments):
        action: Action = {}
        served_set = set()
        for v, p_idx in enumerate(choice):
            plan = vehicle_plans[v][p_idx]
            if plan["served_idx"]:
                action[v] = list(plan["route"])
                served_set.update(plan["served_idx"])
        served_idx = sorted(served_set)
        x = build_feature_vector(state, action, pending, served_idx, P_dummy,
                                 service_time=1.0)
        vhat = relu_model.predict(x)
        rows.append((assign_id, len(served_set), vhat, x))

    rows.sort(key=lambda r: (-r[1], -r[2]))

    print("\nassignment_id | served | Vhat        | x")
    print("-----------------------------------------------")
    for assign_id, served, vhat, x in rows:
        print(f"{assign_id:12d} | {served:6d} | {vhat:10.4f} | "
              f"[{x[0]:.3f}, {x[1]:.3f}, {x[2]:.3f}, {x[3]:.3f}, "
              f"{x[4]:.3f}, {x[5]:.3f}, {x[6]:.3f}]")

    print("===== END VFA DIAGNOSTIC =====\n")

def tiny_demo():
    coords, tt = make_grid(5, 10.0)
    P_dummy = make_dummy_points(JOINT_GRID_SIDE, 2.0)

    samples = build_training_samples(coords, tt, P_dummy,
                                     n_samples=TRAIN_SAMPLES)
    relu = train_relu_vfa_torch(samples, hidden=RELU_HIDDEN,
                                lr=1e-3, n_epochs=50, batch_size=32)

    print(f"[train] torch VFA  ||W1||, ||W2|| via extract:")
    W1, b1, W2, b2 = extract_relu_weights(relu)
    print(f"       hidden={W1.shape[0]}  ||W1||_inf={np.max(np.abs(W1)):.3f}  "
          f"||W2||_inf={np.max(np.abs(W2)):.3f}  |b2|={abs(b2):.3f}")

    preds = [abs(relu.predict(x)) for (x, _) in samples]
    med = float(np.median(preds)) if preds else 0.0
    vfa_scale = calibrate_scale(relu, samples, target=CALIB_TARGET)
    print(f"[calib] median|Vhat| = {med:.3f}  target={CALIB_TARGET:.3f}  "
          f"scale={vfa_scale:.3f}")

    P_dummy_test = P_dummy
    acc_h = run_heuristic_episode(coords, tt, P_dummy_test, steps=150)
    print("Heuristic accepted:", acc_h)

    vehicles = make_initial_vehicles(coords)
    st2 = State(10.0, 0.0, tt, coords,
                [Vehicle(v.id, v.capacity, v.time, v.node, v.load)
                 for v in vehicles])
    acc_vfa = run_episode(st2, P_dummy_test, relu,
                          lam=LAMBDA_VFA, vfa_scale=vfa_scale,
                          steps=150, service_time=1.0)
    print("Batch MILP + ReLU-VFA accepted:", acc_vfa)

    return relu, vfa_scale, coords, tt, P_dummy

if __name__ == "__main__":
    # 1) Heuristic-based advantage training (offline)
    relu_b, vfa_scale_b, coords, tt, P_dummy = tiny_demo()

    # 2) On-policy advantage training using MILP+VFA policy from step 1
    samples_on = build_training_samples_onpolicy(
        coords, tt, P_dummy,
        relu_model=relu_b,
        vfa_scale=vfa_scale_b,
        n_samples=TRAIN_SAMPLES
    )
    relu_on = train_relu_vfa_torch(samples_on, hidden=RELU_HIDDEN,
                                   lr=1e-3, n_epochs=50, batch_size=32)
    vfa_scale_on = calibrate_scale(relu_on, samples_on, target=CALIB_TARGET)

    # 3) Compare baseline VFA vs on-policy VFA
    print_all_results(
        coords, tt, P_dummy,
        relu_batch=relu_b,      vfa_scale_batch=vfa_scale_b,      lam_batch=LAMBDA_VFA,
        relu_joint=relu_on,     vfa_scale_joint=vfa_scale_on,     lam_joint=LAMBDA_VFA,
        steps=150, n_runs=50, seed0=2025,
    )

    # 4) Diagnostic: does Vhat vary across actions?
    diagnose_vfa_one_epoch(relu_on)